templates/master.yaml
That's where it belongs, cfr. https://www.freedesktop.org/software/systemd/man/systemd.unit.html
Fixes the error: `Unknown lvalue 'StartLimitIntervalSec' in section 'Service'`
=> Move StartLimitIntervalSec to Unit section

Makefile, bindata.go, circle.yml
And check on CircleCI that it has the right data.
Depends on #17
=> Makefile: make bindata file deterministic

README.md, tools/update-bindata-hook
This should be manually symlinked into `.git/hooks/pre-commit`.
=> Add hook to generate bindata when templates change

templates.go
These were found while working on https://github.com/giantswarm/aws-operator/pull/70
=> templates: misc fixes

encrypt.go, templates.go
Make the TLS assets available to the workers.
=> Add worker assets to template

encrypt.go, templates.go
According to the naming scheme we've agreed upon.
=> CACrt should be simply CA

templates.go
IP pool has to be added and defined on the every node.
=> templates: Add Calico IP pool on workers

templates.go
=> templates: Remove call to the external etcd cluster

templates.go
Towards https://github.com/giantswarm/aws-operator/issues/133
We don't currently need to serve etcd on a domain,
so this changeset moves etcd to only serve on localhost.
=> Moves etcd to only serve on localhost

templates.go
Fixes giantswarm/aws-operator#134
=> templates: Remove custom /etc/hosts files

templates.go
=> templates: Configure SSL connection to etcd in Calico

templates.go
Towards giantswarm/giantswarm#1388
This PR ensures the https scheme is used for all connections to etcd.
=> Use https scheme for etcd

templates.go
=> templates: Add wait-for-domains service

templates.go
we had forgotten the 4 IC API calls
=> fixing missing templating changes

templates.go
Add missing IP to fix template error.
=> Fix cluster dns ip in kubelet unit

cloudconfig.go, fake_operator.go, operator.go, templates.go
Ref giantswarm/k8scloudconfig#80
=> Move TLS assets from k8scloudconfig to cloud config plugin

cloudconfig.go, fake_operator.go, operator.go, templates.go
Reverts giantswarm/k8scloudconfig#95
=> Revert "Move TLS assets from k8scloudconfig to cloud config plugin"

templates.go
instead of repeating the check multiple times
=> use for loop for wait-for-domains

templates.go
#100
towards giantswarm/giantswarm#1419 and in detail giantswarm/vodafone#128
=> Harden SSH config (#100)

templates.go
this gets networking on aws working
=> removing flannel bridgeip hack from calico unit

templates.go
- update to version 0.9beta5
- adds configmap with hash bucket increase
- fixes ssl port
=> updating and fixing nginx IC

templates.go
to get master node calico working on aws
=> removing bridge ip from calico on master node too

templates.go
My fix to remove the tabs got the indentation wrong
=> Fix indent problem with IC service

cloudconfig.go, cloudconfig_test.go, templates.go
This PR aims to ease the creation of cloud configs.
=> put extension to params to simplify interface

templates.go
WIP
towards https://github.com/giantswarm/k8scloudconfig/issues/116
=> adding kubelet and proxy to master

templates.go
change mounting files to mounting directory to kubelet
not sure if more is needed
=> fixing calico

templates.go
redesign of k8s-addons script
* moving to `kubectl`
* doing retries when `apply` fails
* moving files to array so we don't have to repeat same shit hundred times
ping @giantswarm/team-positive
=> k8s addons v2

templates.go
added port and limits/requests
=> fix for default backend

templates.go
waiting for calico pods to be ready 
script is checking DS `desired` vs `ready`
there is some bash magic :(
ping @giantswarm/team-positive
=> wait for calico to be ready

templates.go
added missing space
ping @giantswarm/team-positive
=> calico ident fix

templates.go
=> fix-k8s-addon-calico-wait2

templates.go
=> fix-k8s-addon-calico-wait3

templates.go
Upstream: https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dns
RFR
=> Updating DNS

templates.go
I had removed/changed this entry, so I'm readding it now
=> fixing DNS for search domains

templates.go
fixing https://github.com/giantswarm/k8scloudconfig/issues/160
=> adding /var/log/pods mount to kubelet

templates.go
update ingress controller image to avoid bugs
=> Update ic image

templates.go
Fixes https://github.com/giantswarm/k8scloudconfig/issues/164
=> Mount whole /var/log into kublet

glide.lock, templates.go, vendor/github.com/giantswarm/clustertpr/spec/kubernetes/ingress.go, vendor/github.com/giantswarm/clustertpr/spec/kubernetes/ingress/docker.go
Towards giantswarm/giantswarm#1695
This PR gets the Ingress controller docker image from the cluster custom object.
=> Ingress version

templates.go
Also set `maxUnavailable: 1` to have higher availability during updates.
Still not sure where to get the worker number from.
=> Making IC K8s 1.7 compatible and setting replicas=#workers

cloudconfig_test.go, templates.go
Towards https://github.com/giantswarm/k8scloudconfig/issues/179
=> Makes calico cidr configurable

templates.go
similar to https://github.com/giantswarm/k8scloudconfig/pull/177 but for worker nodes
we forgot the workers ;)
=> fixing kubelet mount

templates.go
coreos guest  cluster hardening
=> coreos hardening step1

templates.go
=> fix-calico-identation

templates.go
This will disable Docker Legacy Registry v1
=> set --disable-legacy-registry to true

templates.go
Parameter enabled, but not taken into account. Open issue in moby: https://github.com/moby/moby/issues/34909
=> Enable live restore

v_0_1_0/master_template.go, v_0_1_0/worker_template.go
rewrite of https://github.com/giantswarm/k8scloudconfig/pull/200
=> mask-flanneld2

v_0_1_0/master_template.go
towards: https://github.com/giantswarm/giantswarm/issues/1842
* run etcdctl defragmentation once a day at 3.30AM
=> Etcd defragmentation service

v_0_1_0/master_template.go, v_0_1_0/worker_template.go
towards https://github.com/giantswarm/giantswarm/issues/1899
for now i cannot reproduce anymore
=> fix-stuck-in-terminating

v_0_1_0/master_template.go
towards https://github.com/giantswarm/giantswarm/issues/1917
=> upgrade to 1.14.5

v_0_1_0/master_template.go
my bad copy-paste from baremetal template
=> fix-etcd-defrag-cert-path

v_0_1_0/master_template.go, v_0_1_0/worker_template.go
redo of https://github.com/giantswarm/k8scloudconfig/pull/180 for new directory structure
=> adding RBAC and PSP

v_0_1_0/master_template.go
related: https://github.com/giantswarm/giantswarm/issues/1907
add `--experimental-encryption-provider-config` flag to enable data encryption
=> encrypt api server

v_0_1_0/master_template.go
=> update encryption folder path

v_0_1_0/master_template.go
Part of: https://github.com/giantswarm/k8scloudconfig/issues/162
=> Adds calico-node-controller

v_0_1_0/master_template.go
Towards https://github.com/giantswarm/giantswarm/issues/1952
=> enable proxy protocol for ingress-nginx

v_0_1_0/master_template.go, v_0_1_0/worker_template.go
Those services are moved to the `kvm-operator` k8cc specifically
=> Remove iscsid/multipathd services

v_0_1_0/master_template.go
tested in `gauss`
calico-ipip-pinger aims to workaround bug
https://github.com/projectcalico/calico/issues/1173
Part of:https://github.com/giantswarm/giantswarm/issues/1986
=> Adds small component

v_0_1_0/master_template.go
=> etcd-defrag-use-localhost

v_0_1_0/master_template.go
towards: https://github.com/giantswarm/giantswarm/issues/1973
* moved k8s-proxy to daemon set
* added service account for proxy
One of the reason is to have some health check on k8s-proxy
=> Move kube proxy to self-hosted

v_0_1_0/worker_template.go
i forget to remove k8s-proxy also from worker :(
connected to https://github.com/giantswarm/k8scloudconfig/pull/234
=> remove-k8s-proxy-from-worker

v_0_1_0/master_template.go, v_0_1_0/worker_template.go
Towards https://github.com/giantswarm/giantswarm/issues/2024
Adds the changes suggested in https://github.com/giantswarm/giantswarm/issues/1875
=> Upgrade ingress controller

template.go, template_test.go, v1_1/cloudconfig.go, v1_1/cloudconfig_test.go, v1_1/fake_extension.go, v1_1/master_template.go, v1_1/operator.go, v1_1/operator_test.go, v1_1/worker_template.go
Follow up of https://github.com/giantswarm/k8scloudconfig/pull/258.
=> added changes for v1_1 package

template.go, template_test.go, v_1_0_0/cloudconfig.go, v_1_0_0/cloudconfig_test.go, v_1_0_0/fake_extension.go, v_1_0_0/master_template.go, v_1_0_0/operator.go, v_1_0_0/operator_test.go, v_1_0_0/worker_template.go, v_1_1_0/cloudconfig.go, v_1_1_0/cloudconfig_test.go, v_1_1_0/fake_extension.go, v_1_1_0/master_template.go, v_1_1_0/operator.go, v_1_1_0/operator_test.go, v_1_1_0/worker_template.go, v_2_0_0/cloudconfig.go, v_2_0_0/cloudconfig_test.go, v_2_0_0/fake_extension.go, v_2_0_0/master_template.go, v_2_0_0/operator.go, v_2_0_0/operator_test.go, v_2_0_0/worker_template.go
I introduced a simplified versioning scheme which we do not want. This PR moves the existing packages to the same semver approach.
=> use semver versioning scheme

v_3_0_0/cloudconfig.go, v_3_0_0/cloudconfig_test.go, v_3_0_0/fake_extension.go, v_3_0_0/master_template.go, v_3_0_0/operator.go, v_3_0_0/operator_test.go, v_3_0_0/worker_template.go
Copied files with package renamed to v_3_0_0. Package renaming is in a separate commit.
This is a new version to introduce azure-operator changes.
=> v_3_0_0: init from v_2_0_0

v_3_0_0/master_template.go, v_3_0_0/types.go
Towards https://github.com/giantswarm/giantswarm/issues/1384
This is hopefully the last change in cloud configs. It is also the ugliest.
=> v_3_0_0: allow disabling calico

v_3_0_0/master_template.go, v_3_0_0/worker_template.go
Fixes problem introduced in https://github.com/giantswarm/k8scloudconfig/pull/271
I also added test to prevent such things in the future: https://github.com/giantswarm/k8scloudconfig/pull/274
=> v_3_0_0: fix templates Hyperkube references

v_3_0_0/master_template.go
Upgrade Calico to 3.0.1. Tested on geckon.
Partially fixes: https://github.com/giantswarm/giantswarm/issues/2185
=> v_3_0_0: Update Calico to 3.0.1

v_3_0_0/cloudconfig.go, v_3_0_0/cloudconfig_test.go, v_3_0_0/master_template.go, v_3_0_0/types.go
This is a replacement for https://github.com/giantswarm/k8scloudconfig/pull/269 which hangs for a while.
=> v_3_0_0: add apiserver encryption config

CHANGELOG.md, v_3_0_0/master_template.go
tested in `geckon`
Fixes https://github.com/giantswarm/giantswarm/issues/2135
=> v_3_0_0: Replace kube-dns with CoreDNS

v_2_0_1/cloudconfig.go, v_2_0_1/cloudconfig_test.go, v_2_0_1/fake_extension.go, v_2_0_1/master_template.go, v_2_0_1/operator.go, v_2_0_1/operator_test.go, v_2_0_1/worker_template.go
No real changes included.
Following process as described here:
https://github.com/giantswarm/giantswarm/issues/2335#issuecomment-356927360
=> Copy v2_0_0 to v2_0_1

v_3_0_0/master_template.go
Towards https://github.com/giantswarm/giantswarm/issues/1482
Towards https://github.com/giantswarm/giantswarm/issues/2374
Refresh of https://github.com/giantswarm/k8scloudconfig/pull/270
=> v_3_0_0: Adds node-exporter

v_3_0_0/master_template.go, v_3_0_0/worker_template.go
Towards: https://github.com/giantswarm/giantswarm/issues/2374
=> v_3_0_0: update hyperkube to v1.9.2

CHANGELOG.md
Update missing record in Changelog for new k8s version
=> Update Changelog with k8s 1.9.2

CHANGELOG.md, v_3_0_0/master_template.go
Towards https://github.com/giantswarm/giantswarm/issues/1482
Towards https://github.com/giantswarm/giantswarm/issues/2374
=> v_3_0_0: Adds kube-state-metrics

CHANGELOG.md, v_3_0_0/master_template.go
Towards: https://github.com/giantswarm/giantswarm/issues/2374
=> v_3_0_0: update nginx-ingress-controller container to 0.10.1

v_3_1_0/cloudconfig.go, v_3_1_0/cloudconfig_test.go, v_3_1_0/common_template_test.go, v_3_1_0/error.go, v_3_1_0/master_template.go, v_3_1_0/master_template_test.go, v_3_1_0/render_asset_content.go, v_3_1_0/render_asset_content_test.go, v_3_1_0/types.go, v_3_1_0/worker_template.go, v_3_1_0/worker_template_test.go
This PR is the base for future PR with actual changes, related to migration from systemd units to selfhosted k8s components
=> v_3_1_0: init from v_3_0_0

v_3_1_0/master_template.go, v_3_1_0/worker_template.go
Towards: https://github.com/giantswarm/giantswarm/issues/2086
=> v3_1_0: Fix errors and warnings in kube-proxy

v_3_1_0/master_template.go
Towards: https://github.com/giantswarm/giantswarm/issues/2374
=> v3_1_0: Move k8s components to selfhosted pods

v_3_1_1/cloudconfig.go, v_3_1_1/cloudconfig_test.go, v_3_1_1/common_template_test.go, v_3_1_1/error.go, v_3_1_1/master_template.go, v_3_1_1/master_template_test.go, v_3_1_1/render_asset_content.go, v_3_1_1/render_asset_content_test.go, v_3_1_1/types.go, v_3_1_1/worker_template.go, v_3_1_1/worker_template_test.go
=> copy/paste v_3_1_0 to v_3_1_1

CHANGELOG.md, v_3_1_1/cloudconfig.go, v_3_1_1/cloudconfig_test.go, v_3_1_1/common_template_test.go, v_3_1_1/error.go, v_3_1_1/master_template.go, v_3_1_1/master_template_test.go, v_3_1_1/render_asset_content.go, v_3_1_1/render_asset_content_test.go, v_3_1_1/types.go, v_3_1_1/worker_template.go, v_3_1_1/worker_template_test.go
I see potential in doing patch changes in batches.
This change just adds "dev"/WIP version for future patches.
First candidate is new Calico 3.0.2 cc: @calvix
=> New WIP patch version v_3_1_1

CHANGELOG.md, v_3_1_1/master_template.go
Towards https://github.com/giantswarm/aws-operator/issues/651
Added as first change of 3.1.1.
=> Change default etcd data dir to /var/lib/etcd

v_3_1_1/master_template.go
=> upgrade to calico 3.0.2

v_3_1_1/cloudconfig.go, v_3_1_1/master_template.go, v_3_1_1/types.go
Towards: https://github.com/giantswarm/azure-operator/pull/127
=> v3_1_1: Remove azure workarounds for API server

v2_0_2/cloudconfig.go, v2_0_2/cloudconfig_test.go, v2_0_2/fake_extension.go, v2_0_2/master_template.go, v2_0_2/operator.go, v2_0_2/operator_test.go, v2_0_2/worker_template.go
Towards giantswarm/giantswarm#2598
Copy PR for new patch version v_2_0_2.
=> Copy v_2_0_1 to v_2_0_2

CHANGELOG.md, v_3_1_1/master_template.go
Towards https://github.com/giantswarm/giantswarm/issues/2550
=> Add feature gate flag in api server to enable expand PV

CHANGELOG.md, v_3_1_1/master_template.go, v_3_1_1/worker_template.go
Towards https://github.com/giantswarm/giantswarm/issues/2523
=> Adapt kubelet flags to protect kube resources

CHANGELOG.md, v_3_2_1/master_template.go
Towards https://github.com/giantswarm/giantswarm/issues/2656
=> Enable aggregation layer for k8s api server

CHANGELOG.md, v_3_2_2/master_template.go
Towards: https://github.com/giantswarm/giantswarm/issues/2590
=> Remove set-ownership-etcd-data-dir.service

CHANGELOG.md, v_3_2_3/master_template.go
Towards https://github.com/giantswarm/giantswarm/issues/2751
=> v_3_2_3: remove hard limits from core cluster components

CHANGELOG.md, v_3_2_4/master_template.go, v_3_2_4/worker_template.go
Fixes: https://github.com/giantswarm/giantswarm/issues/2862
See bug: https://github.com/systemd/systemd/issues/8524
=> v_3_2_4: Workaround for systemd-networkd behavior

CHANGELOG.md, v_3_2_4/master_template.go, v_3_2_4/worker_template.go
Adds all recommended and one mandatory (in kube-controller-manger) change to enable volume resizing.
Fixes: https://github.com/giantswarm/giantswarm/issues/2861
Depends on: https://github.com/giantswarm/k8scloudconfig/pull/336
=> v_3_2_4: Fix volume resizing

CHANGELOG.md, v_3_2_4/cloudconfig_test.go, v_3_2_4/master_template.go, v_3_2_4/types.go
This is properly tested on ginger via https://github.com/giantswarm/aws-operator/pull/870.
=> removes injection of unencrypted Kubernetes encryption key

v_3_2_5/master_template.go
towards https://github.com/giantswarm/giantswarm/issues/2839
increase the request to 125Mi
=> increase-node-exporter-mem

CHANGELOG.md
just a small typo fix in changelog
=> v_3_2_5: Remove duplicate in changelog

CHANGELOG.md, v_3_2_5/master_template.go
Towards https://github.com/giantswarm/giantswarm/issues/2959
=> Update kube state metrics to 1.3.0

CHANGELOG.md, v_3_2_5/master_template.go
=> v_3_2_5: updated etcd to 3.3.3

CHANGELOG.md, v_3_2_6/master_template.go
Towards https://github.com/giantswarm/vodafone/issues/324
=> Name ports for node exporter

v_3_3_0/cloudconfig.go, v_3_3_0/cloudconfig_test.go, v_3_3_0/common_template_test.go, v_3_3_0/error.go, v_3_3_0/master_template.go, v_3_3_0/master_template_test.go, v_3_3_0/render_asset_content.go, v_3_3_0/render_asset_content_test.go, v_3_3_0/types.go, v_3_3_0/worker_template.go, v_3_3_0/worker_template_test.go
=> copy v_3_2_6 to v_3_3_0

CHANGELOG.md, v_3_3_0/master_template.go, v_3_3_0/worker_template.go
Required for Azure disk issue: https://github.com/giantswarm/giantswarm/issues/2865
=> v_3_3_0: update hyperkube to 1.10.2

CHANGELOG.md, v_3_3_1/master_template.go
towards https://github.com/giantswarm/adidas/issues/320 goes with https://github.com/giantswarm/retagger/pull/85
=> move to retagged images

CHANGELOG.md, v_3_3_1/master_template.go, v_3_3_1/worker_template.go
Fixes: https://github.com/giantswarm/giantswarm/issues/3236
=> v_3_3_1: Fix mkfs.xfs for containerized kubelet

v_3_3_3/cloudconfig.go, v_3_3_3/cloudconfig_test.go, v_3_3_3/common_template_test.go, v_3_3_3/error.go, v_3_3_3/master_template.go, v_3_3_3/master_template_test.go, v_3_3_3/render_asset_content.go, v_3_3_3/render_asset_content_test.go, v_3_3_3/types.go, v_3_3_3/worker_template.go, v_3_3_3/worker_template_test.go
=> copy v_3_3_2 to v_3_3_3

v_3_3_2/master_template.go
=> fix typo in 3.3.2

v_3_3_4/master_template.go, v_3_3_4/worker_template.go
before this we had and possible race condition which we catched on azure here: https://github.com/giantswarm/azure-operator/pull/230#issuecomment-396297396
=> add dependency for k8s kubelet

CHANGELOG.md
set 3.3.4 as stable
set 3.4.0 as WIP
=> make-3_4_0_WIP

CHANGELOG.md, v_3_3_4/master_template.go, v_3_4_0/master_template.go, v_3_4_0/types.go, v_3_4_0/worker_template.go
Towards: https://github.com/giantswarm/giantswarm/issues/2867
=> Add trusted CA into sshd config

CHANGELOG.md, v_3_4_0/master_template.go
enable scraping of IC
towards https://github.com/giantswarm/giantswarm/issues/3537
=> enable-monitoring-for-IC

CHANGELOG.md, v_3_4_0/cloudconfig.go, v_3_4_0/master_template.go, v_3_4_0/types.go, v_3_4_0/worker_template.go
Adds parameter for registry domain, defaults to `quay.io`.
=> Parameterize image registry

CHANGELOG.md, v_3_4_0/master_template.go, v_3_4_0/worker_template.go
Towards https://github.com/giantswarm/giantswarm/issues/1918.
=> adds feature gate for status subresources for CRDs

CHANGELOG.md
Freezes v_3_4_0
Adds v_3_5_0 as new WIP
=> Make v_3_5_0 WIP

CHANGELOG.md
Freezes v_3_5_0 and makes v_3_6_0 WIP.
=> Make v_3_6_0 WIP

v_3_6_0/master_template.go
Thx @puja108 for catching this!
=> Do not remove network policy with coredns manifests

CHANGELOG.md, v_4_0_0/master_template.go
towards https://github.com/giantswarm/giantswarm/issues/4211
=> Update api args

v_3_6_1/cloudconfig.go, v_3_6_1/cloudconfig_test.go, v_3_6_1/common_template_test.go, v_3_6_1/error.go, v_3_6_1/master_template.go, v_3_6_1/master_template_test.go, v_3_6_1/render_asset_content.go, v_3_6_1/render_asset_content_test.go, v_3_6_1/types.go, v_3_6_1/worker_template.go, v_3_6_1/worker_template_test.go
Plain copy of `v3.6.0` -> `v3.6.1`.
=> Copy v3.6.0 -> v3.6.1

CHANGELOG.md, v_3_6_1/master_template.go, v_3_6_1/worker_template.go, v_4_0_0/master_template.go, v_4_0_0/worker_template.go
Towards https://github.com/giantswarm/giantswarm/issues/4187
=> Use patched k8s 1.11.1 for v3.6.1 and 4.0.0

v_4_0_0/files/conf/k8s-addons, v_4_0_0/files/k8s-resource/priority_classes.yaml, v_4_0_0/master_template.go
Towards https://github.com/giantswarm/giantswarm/issues/3405
We can't reuse default priority classes in non system namespace
=> Add giantswarm priority class

v_4_0_0/files/config/kubelet-config.yaml.tmpl, v_4_0_0/master_template.go
Towards https://github.com/giantswarm/giantswarm/issues/4447
=> Remove staticPodPath for workers

v_3_7_0/cloudconfig.go, v_3_7_0/cloudconfig_test.go, v_3_7_0/common_template_test.go, v_3_7_0/error.go, v_3_7_0/master_template.go, v_3_7_0/master_template_test.go, v_3_7_0/render_asset_content.go, v_3_7_0/render_asset_content_test.go, v_3_7_0/types.go, v_3_7_0/worker_template.go, v_3_7_0/worker_template_test.go
purpose is to upgrade to k8s 1.12.1. this is just an empty copy so that
we can see the actual changes in a followup PR.
=> add v_3_7_0

CHANGELOG.md, v_3_7_0/master_template.go, v_3_7_0/worker_template.go
* add clusterCIDR to proxy config for off-cluster bridging
* add dbus socket to proxy
* update addons kubelet to 1.12
=> proxy fixes for 1.12

CHANGELOG.md, v_3_7_2/master_template.go
to make sure that etcd dns is really working we need to check more
often. we have switched back to a loadbalancer and the dns propagation
takes some time. sometimes it resolves correctly but the next one will
fail again.
=> (addons) check etcd dns 10 times

v_3_5_2/master_template.go, v_3_5_2/worker_template.go, v_3_6_3/master_template.go, v_3_6_3/worker_template.go, v_3_7_3/cloudconfig.go
CVE-2018-1002105: proxy request handling in kube-apiserver can leave
vulnerable TCP connections
https://github.com/kubernetes/kubernetes/issues/71411
=> upgrade hyperkube images

v_4_0_0/cloudconfig.go, v_4_0_0/cloudconfig_test.go
It is used in the rendering of the template so should be available as a default parameter
=> Move etcdPort into default params

CHANGELOG.md, DCO, v_4_0_0/files/conf/k8s-addons, v_4_0_0/files/config/kube-proxy.yaml
Towards https://github.com/giantswarm/giantswarm/issues/4975
=> Enable IPVS in kube-proxy

CHANGELOG.md
Follow up of https://github.com/giantswarm/k8scloudconfig/pull/487.
=> add changelog for worker node labels

Gopkg.lock, Gopkg.toml, vendor/github.com/giantswarm/apiextensions/LICENSE, vendor/golang.org/x/net/http2/server.go
Switch from non-existing branch
=> Switch apiextensions to master

CHANGELOG.md, v_3_5_3/cloudconfig.go, v_3_5_3/cloudconfig_test.go, v_3_5_3/common_template_test.go, v_3_5_3/error.go, v_3_5_3/master_template.go, v_3_5_3/master_template_test.go, v_3_5_3/render_asset_content.go, v_3_5_3/render_asset_content_test.go, v_3_5_3/types.go, v_3_5_3/worker_template.go, v_3_5_3/worker_template_test.go, v_3_6_4/cloudconfig.go, v_3_6_4/cloudconfig_test.go, v_3_6_4/common_template_test.go, v_3_6_4/error.go, v_3_6_4/master_template.go, v_3_6_4/master_template_test.go, v_3_6_4/render_asset_content.go, v_3_6_4/render_asset_content_test.go, v_3_6_4/types.go, v_3_6_4/worker_template.go, v_3_6_4/worker_template_test.go
Towards https://github.com/giantswarm/giantswarm/issues/5334
=> Add new packages for CoreOS 1967.5.0

v_4_0_0/cloudconfig.go, v_4_0_0/render_asset_content.go, v_4_1_0/cloudconfig.go, v_4_1_0/render_asset_content.go
This could help to debug the still annoying issue with cloudconfig template appeared yesterday in e2e test
=> Enrich template error with stacktraces

v_4_1_0/files/conf/install-debug-tools
Script fails in azure without this
=> Fix install-debug-tools script

v_3_8_0/master_template.go, v_3_8_0/worker_template.go, v_4_1_0/master_template.go, v_4_1_0/worker_template.go
LOL. I just found I moved those flags into kubelet config file as flags were deprecated :D
Reverts giantswarm/k8scloudconfig#492
=> Revert "Bring resource reservation back"

v_4_1_0/files/manifests/k8s-controller-manager.yaml
Add missing controller-manager mount
=> Fix mounts in controller-manager

v_4_1_0/files/conf/hardening.conf
Towards https://github.com/giantswarm/giantswarm/issues/5418
=> Add a new limit of map count

CHANGELOG.md, v_4_1_1/files/k8s-resource/calico-all.yaml, v_4_1_2/files/k8s-resource/calico-all.yaml
Towards giantswarm/giantswarm#5584
Also see discussion here: https://gigantic.slack.com/archives/C3S482Z98/p1553159399026800
=> Pin calico kube controllers to master

CHANGELOG.md, v_4_1_2/files/k8s-resource/calico-all.yaml
Towards https://github.com/giantswarm/giantswarm/issues/5638, details: https://github.com/giantswarm/giantswarm/issues/5638#issuecomment-477175818
=> Enable serviceaccount calico-kube-controller

v_4_1_2/master_template.go, v_4_1_2/worker_template.go
My typo on rendering from previous PR :/
=> Fix kubelet configs rendering

CHANGELOG.md, v_4_2_0/files/conf/sshd_config
Towards https://github.com/giantswarm/giantswarm/issues/5507
=> Remove deprecated sshd option

CHANGELOG.md, v_4_1_1/master_template.go, v_4_1_1/worker_template.go, v_4_1_2/master_template.go, v_4_1_2/worker_template.go, v_4_2_0/master_template.go, v_4_2_0/worker_template.go
fix race condition issues with systemd dependency in units see https://github.com/giantswarm/giantswarm/issues/5692
This  mainly to help fix flaky e2e test where the race condition appeared more often
also backporting to older version to have all e2e fixed ( both WIP and CUR tests)
=> Fix systemd race issue

v_4_3_0/master_template.go, v_4_3_0/worker_template.go
It is safer for us to have this label as well, since we get warnings anyway.
Read https://gigantic.slack.com/archives/C3S482Z98/p1556634734010100 for more information.
=> Add old role label as well

v_4_3_0/files/k8s-resource/calico-all.yaml
By customer request add label for managed app to calico too
=> Add managed giantswarm label to calico daemonset

CHANGELOG.md, v_4_4_0/files/manifests/k8s-api-server.yaml, v_4_4_0/files/manifests/k8s-controller-manager.yaml, v_4_4_0/files/manifests/k8s-scheduler.yaml
Towards https://github.com/giantswarm/giantswarm/issues/4033
=> Add labels for core components

CHANGELOG.md, v_4_5_0/files/conf/k8s-addons
Towards https://github.com/giantswarm/giantswarm/issues/4033
=> Add namespaces labels

v_4_5_0/files/conf/k8s-addons
=> Fix labeling loop

CHANGELOG.md
For preparation to get 1.14.3 out the door.
=> Add new WIP 4.6.0

CHANGELOG.md, v_4_6_0/files/k8s-resource/psp_policies.yaml
Towards https://github.com/giantswarm/giantswarm/issues/5128
=> Harden default restricted PSP

v_4_6_0/files/k8s-resource/psp_policies.yaml
=> Set restricted psp allowPrivilegeEscalation=false

v_4_6_0/files/config/kubelet-master.yaml.tmpl, v_4_6_0/files/config/kubelet-worker.yaml.tmpl
=> Adjust CPU reserved

v_4_6_0/master_template.go, v_4_6_0/worker_template.go
Following https://github.com/giantswarm/k8scloudconfig/pull/563 , only owner is not enough. Also proper file mode required
=> Add read access for group owner of the certs

v_4_6_0/cloudconfig.go
Signed-off-by: Salvatore Mazzarino <apocalipse89@gmail.com>
=> k8s 1.14.5 ported in 4.6.0

CHANGELOG.md, v_4_7_0/files/manifests/k8s-api-server.yaml, v_4_7_0/files/manifests/k8s-controller-manager.yaml, v_4_7_0/files/manifests/k8s-scheduler.yaml, v_4_7_0/master_template.go, v_4_7_0/worker_template.go
_Towards https://github.com/giantswarm/giantswarm/issues/5925_
=> enable TTLAfterFinished feature gate

v_4_7_0/files/k8s-resource/psp_bindings.yaml
Towards https://github.com/giantswarm/giantswarm/issues/6765#event-2572506429
=> Remove IC binding to privileged PSP

CHANGELOG.md, v_4_7_0/cloudconfig.go, v_4_7_0/files/k8s-resource/calico-all.yaml
Tested on AWS,KVM and Azure.
Did not see any issues.
=> Update k8s to 1.14.6

v_4_9_0/cloudconfig.go, v_4_9_0/cloudconfig_test.go, v_4_9_0/common_template_test.go, v_4_9_0/error.go, v_4_9_0/filemanager.go, v_4_9_0/filemanager_test.go, v_4_9_0/master_template.go, v_4_9_0/master_template_test.go, v_4_9_0/render_asset_content.go, v_4_9_0/render_asset_content_test.go, v_4_9_0/types.go, v_4_9_0/worker_template.go, v_4_9_0/worker_template_test.go
Towards https://github.com/giantswarm/giantswarm/issues/6431
=> Rename package from v_4_8_0 to v_4_9_0

CHANGELOG.md, v_5_0_0/files/config/kubelet-master.yaml.tmpl, v_5_0_0/files/config/kubelet-worker.yaml.tmpl
Towards https://github.com/giantswarm/giantswarm/issues/7575
Rationale: https://github.com/giantswarm/giantswarm/issues/7575#issuecomment-554354878
=> Add hard evinction for image fs (docker volume)

CHANGELOG.md, v_5_0_0/files/k8s-resource/psp_policies.yaml
Make restricted PSP more secure
See https://github.com/giantswarm/giantswarm/issues/7643
=> Make restricted PSP more secure

CHANGELOG.md, v_5_0_0/files/conf/hardening.conf, v_5_0_0/files/config/kube-proxy.yaml
Temporarily disable ipvs mode on azure to fix issue https://github.com/giantswarm/giantswarm/issues/7772 while we wait for a better solution as of https://github.com/giantswarm/giantswarm/issues/7796
=> Disable ipvs on azure

v_4_9_0/worker_template.go, v_5_0_0/worker_template.go
towards giantswarm/giantswarm/issues/7307
=> Set permissions and ownership on fluentbit log dir

CHANGELOG.md, v_5_1_0/files/conf/logentries.sh, v_5_1_0/master_template.go, v_5_1_0/types.go, v_5_1_0/worker_template.go
Splitting this PR https://github.com/giantswarm/azure-operator/pull/641/files
Towards https://github.com/giantswarm/giantswarm/issues/6334
=> Add debug options

CHANGELOG.md, v_5_1_0/files/config/kubelet-master.yaml.tmpl, v_5_1_0/files/config/kubelet-worker.yaml.tmpl
Towards https://github.com/giantswarm/giantswarm/issues/8361
=> Increase kubelet hard memory eviction

CHANGELOG.md
=> Keep correct pattern in changelog

v_5_1_1/cloudconfig.go, v_5_1_1/cloudconfig_test.go, v_5_1_1/common_template_test.go, v_5_1_1/error.go, v_5_1_1/filemanager.go, v_5_1_1/filemanager_test.go, v_5_1_1/master_template.go, v_5_1_1/master_template_test.go, v_5_1_1/render_asset_content.go, v_5_1_1/render_asset_content_test.go, v_5_1_1/types.go, v_5_1_1/worker_template.go, v_5_1_1/worker_template_test.go
Fixing imports [for v5.1.1](https://github.com/giantswarm/k8scloudconfig/pull/644).
=> v5.1.1: imports

CHANGELOG.md, v_5_2_0/master_template.go, v_5_2_0/worker_template.go
Towards https://github.com/giantswarm/giantswarm/issues/1138
=> Enable docker metrics endpoint for prometheus

v_5_2_0/files/k8s-resource/calico-all.yaml
Missing values from https://github.com/aws/amazon-vpc-cni-k8s/blob/master/config/v1.6/calico.yaml
=> Set values from awscni

v_5_2_0/files/k8s-resource/calico-all.yaml, v_5_2_0/files/k8s-resource/calico-policy-only.yaml
Should we set this for AWS only? Is this file shared with Azure?
=> Set values on policy only

CHANGELOG.md, v_6_0_0/cloudconfig.go, v_6_0_0/error.go, v_6_0_0/files/conf/install-debug-tools, v_6_0_0/files/k8s-resource/calico-all.yaml, v_6_0_0/files/k8s-resource/kube-proxy-ds.yaml, v_6_0_0/files/manifests/k8s-api-healthz.yaml, v_6_0_0/files/manifests/k8s-api-server.yaml, v_6_0_0/files/manifests/k8s-controller-manager.yaml, v_6_0_0/files/manifests/k8s-scheduler.yaml, v_6_0_0/master_template.go, v_6_0_0/release.go, v_6_0_0/types.go, v_6_0_0/worker_template.go
Towards https://github.com/giantswarm/giantswarm/issues/8436
=> v6.0.0: Make images and versions all template-able

CHANGELOG.md
=> release v6.0.1

CHANGELOG.md, v_4_9_1/files/k8s-resource/calico-all.yaml
=> Remove init limits for calico

CHANGELOG.md, v_4_9_1/files/config/kube-proxy.yaml, v_6_0_0/files/config/kube-proxy.yaml
=> legacy: Increase conntrack max (#659)

v_6_0_0/files/conf/wait-for-domains
=> Hardcode registry domain to avoid template rendering issues

v_4_9_2/cloudconfig.go, v_4_9_2/cloudconfig_test.go, v_4_9_2/common_template_test.go, v_4_9_2/error.go, v_4_9_2/filemanager.go, v_4_9_2/filemanager_test.go, v_4_9_2/master_template.go, v_4_9_2/master_template_test.go, v_4_9_2/release.go, v_4_9_2/render_asset_content.go, v_4_9_2/render_asset_content_test.go, v_4_9_2/types.go, v_4_9_2/worker_template.go, v_4_9_2/worker_template_test.go
Follows https://github.com/giantswarm/k8scloudconfig/pull/697
=> v4.9.2 imports

v_6_0_0/files/conf/k8s-addons, v_6_0_0/files/k8s-resource/calico-all.yaml, v_6_0_0/files/k8s-resource/calico-policy-only.yaml, v_6_0_0/files/k8s-resource/ingress-controller-svc.yaml, v_6_0_0/files/k8s-resource/kube-proxy-ds.yaml, v_6_0_0/files/manifests/k8s-api-server.yaml, v_6_0_0/files/manifests/k8s-controller-manager.yaml, v_6_0_0/files/manifests/k8s-scheduler.yaml
I am keeping this as a draft because it will probably have a lot of things to do.
What would be the next steps?
=> Add common labels

CHANGELOG.md
=> Release v6.0.3

CHANGELOG.md, files/config/kube-proxy.yaml
=> Fix conntrack config structure for kube-proxy

CHANGELOG.md
=> Release 6.1.0 of k8scc

CHANGELOG.md
=> Release v6.1.1

CHANGELOG.md, files/k8s-resource/calico-all.yaml
Towards https://github.com/giantswarm/giantswarm/issues/10543
=> Remove limits calico-kube-controller

CHANGELOG.md, files/k8s-resource/calico-all.yaml
=> Add bird live flag

CHANGELOG.md, pkg/template/master_template.go, pkg/template/worker_template.go
Towards https://github.com/giantswarm/giantswarm/issues/11085
Going to test on a kvm env.
=> Ensure rpc-statd.service is running before kubelet

CHANGELOG.md
=> update changelog for 6.2.2 release

CHANGELOG.md
=> release-6.2.3

CHANGELOG.md, pkg/template/worker_template.go
=> Use .Images.KubernetesNetworkSetupDocker for worker also

CHANGELOG.md, files/config/kube-proxy.yaml, pkg/template/worker_template.go
=> Drop kube-proxy clusterCIDR for Azure as well

CHANGELOG.md
=> release v6.2.4

CHANGELOG.md, files/conf/docker-daemon.json, pkg/template/master_template.go, pkg/template/worker_template.go
Towards https://github.com/giantswarm/giantswarm/issues/11327
=> Add quay.io as registry mirror in dockerd config

CHANGELOG.md, pkg/template/master_template.go, pkg/template/worker_template.go
Towards https://github.com/giantswarm/giantswarm/issues/11573
=> Use docker hub pod infra

.github/workflows/zz_generated.create_release.yaml, .github/workflows/zz_generated.create_release_pr.yaml
=> Add github workflows for releases

CHANGELOG.md, files/conf/docker-daemon.json, pkg/template/master_template.go, pkg/template/worker_template.go
=> Revert registry mirrors over security concerns

CHANGELOG.md
=> release v6.2.6

files/conf/wait-for-domains
Fixes https://github.com/giantswarm/giantswarm/issues/11843
=> files/conf: add back external domain to wait-for-domains

CHANGELOG.md, pkg/template/master_template.go, pkg/template/release.go, pkg/template/worker_template.go
Towards https://github.com/giantswarm/giantswarm/issues/11838
=> template: add back registry but allow short names

CHANGELOG.md, pkg/template/master_template.go, pkg/template/release.go, pkg/template/worker_template.go
Towards https://github.com/giantswarm/giantswarm/issues/11838
For Docker Hub we can use "docker.io".
=> template: do not support empty registry domain

pkg/template/master_template.go, pkg/template/release.go, pkg/template/types.go, pkg/template/worker_template.go
Towards https://github.com/giantswarm/giantswarm/issues/11736
=> template: set pause to 3.2

CHANGELOG.md, go.mod, go.sum, pkg/template/cloudconfig.go, pkg/template/cloudconfig_test.go
This PR updates a local module reference that was still using the v6 release.
=> Remove v6 reference

files/conf/docker-daemon.json, pkg/template/master_template.go, pkg/template/worker_template.go
=> Configure Docker in one place

CHANGELOG.md, files/k8s-resource/calico-all.yaml, files/k8s-resource/calico-policy-only.yaml, files/k8s-resource/ingress-controller-svc.yaml, files/k8s-resource/kube-proxy-ds.yaml, files/manifests/k8s-controller-manager.yaml, files/manifests/k8s-scheduler.yaml
Towards: https://github.com/giantswarm/giantswarm/issues/11724
=> add monitoring labels for kube-proxy, k8s-scheduler, k8s-controller-manager

CHANGELOG.md, files/k8s-resource/calico-all.yaml
Cherry-pick of 81dac86091072f3da09331243d43c0f605c0e965 (https://github.com/giantswarm/k8scloudconfig/pull/719) into v6.1.x for https://github.com/giantswarm/giantswarm/issues/12619.
=> Remove limits calico-kube-controller (#719)

CHANGELOG.md
=> release v6.1.3

CHANGELOG.md, files/manifests/k8s-api-server.yaml
I was getting a weird line break, so I tested the template in the playground and I belive it's not correct. You can see it in action here https://play.golang.org/p/SNTCNgB4mHp
=> Fix line break when selecting HA

CHANGELOG.md, files/config/kubelet-master.yaml.tmpl, files/config/kubelet-worker.yaml.tmpl
=> Allow parallel image pulls in kubelet

CHANGELOG.md, files/config/kubelet-master.yaml.tmpl, files/config/kubelet-worker.yaml.tmpl
Improves https://github.com/giantswarm/giantswarm/issues/13480
=> Allow parallel image pulls in kubelet 

CHANGELOG.md, pkg/template/master_template.go, pkg/template/worker_template.go
towards https://github.com/giantswarm/giantswarm/issues/13510
to ensure the important labels are always set even in case the customer does some bad voodoo
=> k8s-label-node-timer

CHANGELOG.md, pkg/template/master_template.go, pkg/template/worker_template.go
Split from https://github.com/giantswarm/k8scloudconfig/pull/801
=> Update kubelet calico etcd cert paths

files/config/kubelet-master.yaml.tmpl, files/config/kubelet-worker.yaml.tmpl, files/manifests/k8s-api-server.yaml
=> Cis flag updates noreadonly

CHANGELOG.md, files/conf/kubelet-docker-config.json, pkg/template/cloudconfig.go, pkg/template/cloudconfig_test.go, pkg/template/master_template.go, pkg/template/types.go, pkg/template/worker_template.go
Towards https://github.com/giantswarm/giantswarm/issues/13981
=> Add dockerhub authentication for kubelet (v9)

CHANGELOG.md, files/conf/kubelet-docker-config.json, pkg/template/cloudconfig.go, pkg/template/cloudconfig_test.go, pkg/template/master_template.go, pkg/template/types.go, pkg/template/worker_template.go
Towards giantswarm/giantswarm#13981
=> Add dockerhub authentication for kubelet (v7)

CHANGELOG.md, pkg/template/master_template.go, pkg/template/worker_template.go
=> Set root user for k8s-kubelet explicitly (v9)

CHANGELOG.md, pkg/template/cloudconfig.go, pkg/template/cloudconfig_test.go, pkg/template/master_template.go, pkg/template/types.go, pkg/template/worker_template.go
Towards https://github.com/giantswarm/giantswarm/issues/13981
=> Add dockerhub authentication for kubelet (v8)

CHANGELOG.md, files/conf/kubelet-docker-config.json
=> Add missing kubelet-docker-config.json file

CHANGELOG.md, files/manifests/k8s-api-server.yaml
=> Enable `anonymous-auth` in API server 

go.sum
=> Make go mod happy again

go.mod, go.sum
=> Update go vulnerabilities

CHANGELOG.md, files/conf/k8s-addons
See https://gigantic.slack.com/archives/CHAHY6VMF/p1620026573179400
=> wait for hostname to be set

CHANGELOG.md, files/config/kubelet-master.yaml.tmpl, files/manifests/k8s-api-server.yaml
=> add service account changes

CHANGELOG.md, pkg/template/master_template.go, pkg/template/types.go, pkg/template/worker_template.go
=> Add proxies to the master and worker templates

CHANGELOG.md, pkg/template/worker_template.go
Signed-off-by: Salvatore Mazzarino <dev@mazzarino.cz>
=> Remove tabs

CHANGELOG.md, files/config/kubelet-master.yaml.tmpl, files/config/kubelet-worker.yaml.tmpl
related to: https://github.com/giantswarm/giantswarm/issues/11509
=> set kernelMemcgNotification kubelet config to true

CHANGELOG.md, files/conf/k8s-addons, pkg/template/master_template.go
=> Avoid running Calico datastore migration pods when Calico is in policy only mode

CHANGELOG.md, files/conf/k8s-addons
this part was recently refactorized and aws was without calico-policy only, fixing the bug
=> fix-aws-cni-file

CHANGELOG.md, files/k8s-resource/calico-all.yaml, pkg/template/release.go, pkg/template/release_test.go, pkg/template/types.go
Towards https://github.com/giantswarm/giantswarm/issues/19003
=> Add calico-typha for KVM

CHANGELOG.md, files/k8s-resource/calico-policy-only.yaml, pkg/key/key.go
Towards: https://github.com/giantswarm/roadmap/issues/695
Updated calico policy only manifest to support newest calico version
=> Calico 3.21

CHANGELOG.md, files/conf/ensure-cgroups-v1, files/conf/grub.cfg, pkg/template/master_template.go, pkg/template/types.go, pkg/template/worker_template.go
towards https://github.com/giantswarm/roadmap/issues/772
=> support-cgroups-v1

CHANGELOG.md, go.mod, pkg/template/cloudconfig.go, pkg/template/cloudconfig_test.go, pkg/template/validation.go
=> bump-module-version

CHANGELOG.md, files/k8s-resource/psp_policies.yaml
towards https://github.com/giantswarm/roadmap/issues/114
=> add-support-for-service-account-oidc

CHANGELOG.md, go.mod, pkg/template/cloudconfig.go, pkg/template/cloudconfig_test.go, pkg/template/validation.go
=> Bump go module major version to v12

CHANGELOG.md, go.mod, pkg/template/cloudconfig.go, pkg/template/cloudconfig_test.go, pkg/template/validation.go
=> Bump go module major version to v13

CHANGELOG.md, files/k8s-resource/kube-proxy-ds.yaml
Towards: https://github.com/giantswarm/giantswarm/issues/21494
Add VPA config for kube-proxy to optimize resource usage.
=> Add VPA CR for kube-proxy.

CHANGELOG.md, files/k8s-resource/kube-proxy-ds.yaml
=> Remove VPA CR for kube-proxy.

CHANGELOG.md, files/config/kubelet-master.yaml.tmpl, files/config/kubelet-worker.yaml.tmpl, pkg/template/master_template.go, pkg/template/worker_template.go
Towards: https://github.com/giantswarm/roadmap/issues/1090
=> Use systemd Cgroups driver

CHANGELOG.md, pkg/template/master_template.go
File is long gone from this repo and is provided by aws-operator.
=> Remove `aws-cni.yaml` file creation. 

CHANGELOG.md, files/manifests/k8s-api-server.yaml, files/manifests/k8s-controller-manager.yaml, pkg/template/master_template.go, pkg/template/types.go, pkg/template/worker_template.go
Allow to use in-tree cloud controller manager
=> Optional ccm

CHANGELOG.md, files/conf/containerd-config.toml
=> Set `SystemdCgroup` to false in `containerd` config for node pools using cgroups v1

CHANGELOG.md, files/conf/setup-apiserver-environment, files/manifests/k8s-api-server.yaml.tmpl, pkg/template/master_template.go
Towards: https://github.com/giantswarm/giantswarm/issues/23532 and https://github.com/giantswarm/giantswarm/issues/22234#issuecomment-1141952289
This PR automatically sets the `--max-requests-inflight`, `--max-mutating-requests-inflight` and resource limits to API Server's manifest based on node size.
=> Max requests

CHANGELOG.md, files/conf/setup-apiserver-environment, files/manifests/k8s-api-server.yaml.tmpl
Backport of fix from giantnetes-terraform
=> fix apiserver limit calculation +  add request

CHANGELOG.md, files/manifests/k8s-controller-manager.yaml, files/manifests/k8s-scheduler.yaml
Towards: https://github.com/giantswarm/giantswarm/issues/24430#issuecomment-1326589649
=> Add `component` label to scheduler and controller-manager's manifests.

CHANGELOG.md, files/k8s-resource/psp_policies.yaml
test with seccomp wildcard in restricted whether runtime/default was too strict to deploy clusters.
=> draft pull request to check some branch behaviour

CHANGELOG.md, files/conf/setup-kubelet-environment, pkg/template/types.go
=> Add subnet prefix mode to remove pod limit

CHANGELOG.md, files/config/kubelet-master.yaml.tmpl, files/config/kubelet-worker.yaml.tmpl, files/manifests/k8s-api-server.yaml.tmpl, files/manifests/k8s-controller-manager.yaml, files/manifests/k8s-scheduler.yaml
towards: https://github.com/giantswarm/roadmap/issues/1895
=> Cronjob timezone feature gate

CHANGELOG.md, files/manifests/k8s-api-server.yaml.tmpl
Issue: https://github.com/giantswarm/giantswarm/issues/26781
=> Disable ETCD compaction request from apiserver

CHANGELOG.md
=> Release v16.6.1

CHANGELOG.md, files/conf/imds-client, files/conf/setup-kubelet-environment, pkg/template/master_template.go, pkg/template/worker_template.go
Towards: https://github.com/giantswarm/giantswarm/issues/30405
fix imds v2 calls for AWS
=> imds v2 fixes
