giantswarm/k8scloudconfig

operator.go
operator_test.go

External extensions implementes in operator repos (like aws-operator) will use their own templates, that's why we need to allow to template them here.

operator: Use external asset contents instead of internal assets

---

cloudconfig.go
operator.go

If we use html/template, text will be escaped to make it safe.
This is not what we want, we're not dealing with html and it breaks
things like base64-encoded keys and such.

Use text/template, not html/template

---

Makefile

This was done for aesthetics reasons, but it changes the templates every
time since most text editors add a newline at the end.
Also, with the new commit hook introduced in 882419ab6, it leaves a
dirty git worktree after the commit.
Just remove it since we don't care that much about an extra line in the
resulting cloudconfig.

Makefile: don't remove newline at the end of templates

---

templates.go

These assets shouldn't be available on the worker.

Remove apiserver TLS assets from worker template

---

templates.go

templates: Remove etc-kubernetes-ssl.mount

---

templates.go

etcd listens on 2379 and initially advertises on 2380. The port 443 should be used only by the k8s apiserver.
Fixes #45

templates: Fix etcd ports

---

templates.go

Towards https://github.com/giantswarm/aws-operator/issues/138
We moved etcd to use 2380, but missed some instances.
This changeset moves all remaining instances of 2383 to 2380.

Moves all instances of port 2383 to port 2380

---

templates.go

This service is specific only for the aws-oeprator.
Fixes giantswarm/aws-operator#143

templates: Remove decrypt-tls-assets service

---

templates.go

This PR fixes the following issue we found. 
```
$ journalctl -b
...
Apr 24 15:34:24 ip-10-0-141-134.eu-west-1.compute.internal systemd[1]: [/etc/systemd/system/docker.service.d/10-giantswarm-extra-args.conf:2] Trailing garbage, ignoring.
...
```

added missing trailing quotes to unit file

---

templates.go

Towards https://github.com/giantswarm/aws-operator/issues/131
coreos-cloudinit starts unit sequentially, so the order of the
units needs to avoid deadlocks. In the case where the
aws-operator adds decrypt-tls-assets which is a requirement of
the later units, this causes a deadlock.
This changset moves the extension units to the top of the
cloudconfig, to avoid these deadlocks.

Moves extension units to top of cloudconfig

---

templates.go

Fixes https://github.com/giantswarm/k8scloudconfig/issues/62
The addons script posts manifests to the apiserver, and has no
dependency on the scheduler. It makes more logical sense to have
it depend on the apiserver, instead of the scheduler.

Moves addons to require apiserver, instead of scheduler

---

templates.go

Fixes https://github.com/giantswarm/k8scloudconfig/issues/61
This mount is legacy from the older platform, and is not actually
defined anywhere. Cleaning up a little.

Removes etc-kubernetes-data-etcd.mount

---

templates.go

In case the hostname is not properly set, then there is no hostname, which renders the yaml invalid. Having it wrapped in quotes keeps the yaml valid even if there is no hostname defined.

provide double quotes for hostnames to prevent missing value

---

templates.go

--initial-cluster needs to be adjusted to --initial-advertise-peer-urls. We're now using etcd domain in both places.
Fixes #66

templates: Fix address in --initial-advertise-peer-urls

---

templates.go

By default, the DHCP server in AWS points instances to their internal DNS servers, which makes our Route 53 domains available faster.
Fixes giantswarm/aws-operator#178

templates: Don't override /etc/resolv.conf

---

templates.go

Towards giantswarm/giantswarm#1388 and #69
This PR adds an env file in /etc/calico-environment that sets the bridge IP. On AWS this will use the internal IP for the instance. On KVM it needs to be the bridge IP.
Also adds missing cert files when saving the IP to etcd in the master template.

Provide bridge IP to calico node unit

---

templates.go

Fixes indentation problem when rendering a 2nd operator unit in the main cloudconfig.

Fix indent problem with multiple units

---

templates.go

Towards giantswarm/giantswarm#1388 and #70 
Use service account key pair in apiserver and controller-manager units. The aws-operator also needs to be extended to watch for the secret and download and decrypt it.

Use service account key pair in apiserver and controller-manager

---

encrypt.go
templates.go

Towards giantswarm/giantswarm#1388 and fixes #70 
This PR adds service account to the TLS assets and creates the encoded files in the master cloudconfig.

Service account

---

templates.go

Towards #81 
The decrypt unit isn't being written correctly due to this indent error. I've now checked the templates for all instances of this bug and this is the last one.

Fix indent error when writing operator units in the worker template

---

templates.go

Fixes #85 
The controller-manager is not starting because the flag name is wrong.

Fix flag name for the service account private key

---

templates.go

Fixes #87
The etcd certs are named incorrectly in the worker template. They've been renamed to client as a short term solution to unblock AWS testing. 
See #80 we need to move the certificate files to aws-operator as they are AWS specific. We will also eventually need to generate a separate client cert for the workers.

Rename etcd certs to client on the worker

---

templates.go

Towards giantswarm/giantswarm#1388
This PR fixes a problem with the Calico policy controller not starting. The client cert needs to be provided when connecting to etcd.

Use client cert when connecting to etcd

---

templates.go

Since we have `Kubelet.Port` in the `clustertpr`, we should honour it.

Use kubelet port from TPO

---

templates.go

Towards giantswarm/giantswarm#1381
IC pods were crashing because we were using the wrong healthcheck ports for the docker image we're using.

Fix healthcheck port for liveness and readiness probes

---

templates.go

This PR fixes the cluster domain in the kubelet unit. It should use `Cluster.Kubernetes.Domain` and not `Cluster.Kubernetes.API.Domain`.

Fix templating for cluster domain

---

templates.go

this way, we ensure that the whole kubernetes stack waits until the records are there

make calico-node dependent on the DNS records

---

templates.go

etcd doesn't need the DNS records to be present. it's etcd's clients who need it, like calico-node.

remove domains requirement from etcd2

---

operator.go
operator_test.go
templates.go

TLS assets need to use gzip+base64 encoding, so we need to allow to specify encoding by extensions.
Ref #80

extensions: Add "encoding" field to file metadata

---

operator.go
operator_test.go
templates.go

utf-8 is not one of the allowed values for the `encoding` key, because
it's the implicit default value.
This fixes the cloudconfig.
See https://github.com/coreos/coreos-cloudinit/blob/d9e03750a7985103b89aa44574bfe7929007ec20/config/file.go#L18

No encoding key if value is default (utf-8)

---

templates.go

This PR enables all api extensions by default, this way we don't need to manually add and remove runtime-config flags on versions and avoid requests for specific extensions from users.
Also fixes the problem that cronjobs were broken on our clusters.
This also removes a api server flag that was wrong (`--runtime_config`)

enable all api extensions

---

templates.go

it was only there to support the $BRIDGE_IP hack, which was removed in #111

remove unused calico environment file invocation

---

templates.go

I dont see any reason why we should have restart units for:
* k8s proxy
* kubelet
* k8s api server
* k8s controller manager
* k8s scheduler
(etcd is removed in separate PR - https://github.com/giantswarm/k8scloudconfig/pull/124)
WDYT @JosephSalisbury @rossf7 @xh3b4sd

remove restart units

---

templates.go

Towards https://github.com/giantswarm/k8scloudconfig/issues/40
WIP
Running Calico 2.2.1
This is already implemented and tested manually on `wopre` cluster on AWS FRA
TODO:

making calico hosted (and updating to latest)

---

templates.go

Upgrading etcd to etcdv3 and moving etcd to container.
Its working, but it cannot be fully tested because current calico does not support etcdv3 (etcdv3 forces TLS 1.2 and old calico is trying TLS 1.0 ), so we have to wait for https://github.com/giantswarm/k8scloudconfig/pull/123

update etcd version

---

templates.go

Current script only check for etcd domain  and ignores API domain
```
core@ip-10-0-130-47 /etc/systemd/system $ bash /opt/wait-for-domains 
Server:		10.0.0.2
Address:	10.0.0.2#53
Non-authoritative answer:
Name:	etcd.9vkwk.g8s.eu-west-1.adidas.aws.giantswarm.io
Address: 35.157.247.232
Name:	etcd.9vkwk.g8s.eu-west-1.adidas.aws.giantswarm.io
Address: 52.28.36.2
Successfully resolved domain etcd.9vkwk.g8s.eu-west-1.adidas.aws.giantswarm.io
core@ip-10-0-130-47 /etc/systemd/system $ vim /opt/wait-for-domains
```

fix wait for domains

---

templates.go

lets wait until `kubectl get cs` is returning healthy on all components  before k8s-addons is executed

wait for healthy k8s cluster

---

templates.go

based on:
https://github.com/kubernetes/ingress/blob/master/examples/deployment/nginx/nginx-ingress-controller.yaml
https://github.com/kubernetes/ingress/blob/master/examples/deployment/nginx/default-backend.yaml
- update to beta.7
- moved back service to port 443
- use default-backend from upstream
- change naming and healthchecks to be similar to upstream
this is rolled out and tested (with SSL passthrough) on `z5eru`

IC update and sync with upstream

---

templates.go

previous version was checking desired versus current instead of desired versus ready

fix k8s addons calico wait

---

templates.go

There was a namespace missing so it was deploying it to `default`
We didn't realize before, cause with api calls we were calling the namespace anyway. with kubectl we are not and we did not check IC after the move.

fix nginx cm namespace

---

templates.go

Towards https://github.com/giantswarm/giantswarm/issues/1197. There was a Slack conversation around this issue. See https://gigantic.slack.com/archives/C2MS2VB37/p1496756711183060. 
The idea is to align the ports under which etcd is accessible via domain. KVM and AWS should use `etcd.domain:443`. At the moment AWS uses `etcd.domain:2379`, which does not work in KVM, because the Kemps are configured to listen on `443`. The easiest way to align this is to change it for AWS where ELB configuration has to be modified.

changed port for etcd domain from 2379 to 443

---

fake_operator.go
operator.go
templates.go

VerbatimSection represents a generic, top-level piece of YAML that should be
included verbatim in the CloudConfig. i.e. it's neither a `Unit` block, or a `File` block.
Example:
```
storage:
filesystems:
- name: ephemeral1
mount:
device: /dev/xvdb
format: ext3
create:
force: true`
```
The AWS operator needs this for Instance Storage, whereas KVM doesn't. Therefore, we need to be able to inject it in the CloudConfig.
Towards https://github.com/giantswarm/giantswarm/issues/1530.

add VerbatimSection to cloud config

---

templates.go

this is needed so kubelet can mount dynamically provisioned disks like for example EBS

adding kubelet mount

---

templates.go

we have only two services (k8s api and calico)
that use etcd and both of them have certificates
and keys for access.
Fixes https://github.com/giantswarm/giantswarm/issues/1550

Turn etcd auth on

---

templates.go

This fixes issue with pod termination.
Problem is that duplicate volume mounts appear
inside kubelet container. But kubelet
unmounts only one inside /var/lib/kubelet.
Other one looks like this
`/var/lib/docker/overlay/LAYERID/merged/var/lib/kubelet/pods/PODID/.../default-token-8t5b0`
So kubelet ends up with Device or resource busy, when
tries to do smth with parent directory.
I can reproduce problem on local Docker.
My assumption that /var/lib/docker got mounted as shared (not as private),
so when kubelet mounts volume it becoms visible in docker overlay
and propagated inside kubelet second time.
Not sure why it doesn't work other way around for unmount.
BTW such behaviour can be fixed both by making
1) /var/lib/kubelet:rw,shared shared like here
2) /var/lib/docker:rw,private
Good article …

Mount /var/lib/kubelet as shared

---

templates.go

towards https://github.com/giantswarm/giantswarm/issues/1720
tested on `56x77` on ginger
these fixes are all recommended in the CIS benchmark and do not break anything, but make our setup more secure, this is the quickest win we can have in that area, other setting will be harder and will need more thorough testing (mostly cause they need bootstrapping steps)

some quickwin fixes for security

---

templates.go

based on upstream https://docs.projectcalico.org/v2.5/getting-started/kubernetes/installation/hosted/calico.yaml
running succesfully on `totl0` on `ginger`

updated calico to 2.5.1

---

templates.go

towards https://github.com/giantswarm/adidas/issues/134
in future, we may wanna have this configurable, but for now, it's better if we don't have to configure it manually
ip conntrack is for tracking connection for iptables
if this limit is reached iptables is not able to track more connection so the rest is dropped
the implication is just small increase of RAM usage

increase-conntrack-limit

---

v_0_1_0/master_template.go

use correct label and taint for master (leave existing label for compatibility)
See source: https://github.com/kubernetes/kubernetes/pull/41835
use proper tolerations for Calico from kubeadm.
Default Calico manifests contain outdated toleraiotns
See source: https://github.com/projectcalico/calico/blob/master/v2.5/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml#L71-L77
Discussed in detail here: https://github.com/giantswarm/aws-terraform/pull/91

Make master unschedulable with taint

---

v_0_1_0/master_template.go
v_0_1_0/worker_template.go

Disable Userland proxy for Docker
cc @puja108 LGTM, userland proxy was supposed to be disabled by default since Docker 1.7 (it was only needed for old RHEL versions or sth), but still open issue :D

Disable userland

---

v_0_1_0/master_template.go
v_0_1_0/worker_template.go

In AWS nodes already have hostnames and not IPs.
Looks like --cloud-provider=aws takes precedence
over --hostname-overwrite.
So this change DOES NOT change actual behaviour.
We want to use calico-node-controller
that syncronizes nodes from k8s with Calico.
By default k8s and Calico use hostnames,
but we used IP addresses. This change
switches back to hostnames.
Part of https://github.com/giantswarm/k8scloudconfig/issues/162

Use hostnames instead of IP addresses

---

v_0_1_0/master_template.go

By default user needs manually delete pods
after new DaemonSet version applied.
related changes:
https://github.com/giantswarm/aws-terraform/pull/118
https://github.com/giantswarm/hive/pull/146

Rolling update of Calico nodes

---

v_0_1_0/master_template.go
v_0_1_0/worker_template.go

2.1 - Ensure network traffic is restricted between containers on the default bridge
This will disable default `bridge` network on docker daemon.
icc=false should be ok as we are not using docker bridged network.
For me it set drop on following rule, not whole system.
-A FORWARD -i docker0 -o docker0 -j DROP

Disable default bridge

---

v_0_1_0/master_template.go

Enable audit for `api-server` as required by Kubernetes CIS benchmark

k8s CIS benchmark: audit

---

v_0_1_0/master_template.go

fix for https://github.com/giantswarm/k8scloudconfig/pull/207
by default api is accessing machines via hostnames which are not existing in case of kvm

k8s-use-internalIP-for-kubelet

---

v_0_1_0/master_template.go
v_0_1_0/worker_template.go

Towards https://github.com/giantswarm/giantswarm/issues/1901
To control k8s versions through our k8scc I integrated the hyperkube image and version instead of taking the templated variable, we should get rid of that after this PR. This helps us to move to multi-version support in the future.
Other than the update to k8s 1.8.1 I had to fix the kubeconfigs and remove the deprecated flags called api-server/master from the k8s components.
I also added an additional spec to our privileged PSP that came in with k8s 1.8

Update k8s to 1.8.1

---

v_0_1_0/master_template.go

towards https://github.com/giantswarm/giantswarm/issues/1900
syncing with upstream https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/hosted
policy controller has been renamed to kube-controllers
needs testing, will do so on gauss

update calico to 2.6.2

---

v_0_1_0/master_template.go

Regarding this https://github.com/giantswarm/giantswarm/issues/2035: to be relevant if the directory is mounted as a volume in the container
Closes https://github.com/giantswarm/giantswarm/issues/2035

change data directory permission to 700

---

v_0_1_0/master_template.go

Related to https://github.com/giantswarm/giantswarm/issues/1952
The first tests were not executed properly, the actual result is that ingress-nginx with proxy protocol doesn't work as expected on kvm:
```
$ curl http://10.0.4.112:30100/ -H "Host: helloworld.fvx9p.gigantic.io"
curl: (52) Empty reply from server
```
These changes revert the `use-proxy-protocol` setting for the ingress-nginx configmap.

remove proxy protocol config

---

v_0_1_0/master_template.go
v_0_1_0/worker_template.go

Add required mounts for `k8s-kubelet` to make iscsi mounts working in guest cluster

Add iscsi support for guest cluster

---

v_0_1_0/master_template.go

together with https://github.com/giantswarm/kubernetesd/pull/280
towards https://github.com/giantswarm/giantswarm/issues/1905

k8s-use-localhost-for-etcd

---

v_0_1_0/master_template.go

this PR moves `calico-node-controller` to master and remove the need of working calico network in order to work.
I have encountered a scenario when there was deadlock - calico-node was not starting because of duplicate ip and calico-node-controller can't clean the config because networking was not working.
This PR solve this issue.

run-calico-controller-on-master

---

v_0_1_0/master_template.go
v_0_1_0/worker_template.go

if a aws machine is restarted then os-hardening fail since removing `core` from the sudo groups is no longer possible as it was removed at the first start.
adding `-` to indicate sytemd that this command can fail.

os-hard-resiliency

---

v_0_1_0/master_template.go

Regarding k8s CIS benchmark, we need to disable anonymous access to the api and use 0 as insecure port.
Currently, k8s-addons use kubectl with anonymous access. We have to provide a kubeconfig for this. eg. proxy-kubeconfig
in k8scc the insecure port is set by `--insecure_port={{.Cluster.Kubernetes.API.InsecurePort}}`
**question:** is it a problem for us to disable it? and do you prefer to remove insecure port from struct and use `0` directly in k8scc or having `0` as default value in the struct and let the operator overriding it
Rel: https://github.com/giantswarm/giantswarm/issues/2020

Disable anonymous access and insecure port

---

v_0_1_0/master_template.go

Reverts this change https://github.com/giantswarm/k8scloudconfig/pull/224/files#diff-c0ae19d8351967dbe58eae812425f1a7L1532 and aims to prevent this error, which makes guest cluster creation fail:
```
Nov 14 15:10:29 ip-10-1-12-78.eu-central-1.compute.internal bash[888]: 2017/11/14 15:10:29 Checking availability of "local-file"
Nov 14 15:10:29 ip-10-1-12-78.eu-central-1.compute.internal bash[888]: 2017/11/14 15:10:29 Fetching user-data from datasource of type "local-file"
Nov 14 15:10:29 ip-10-1-12-78.eu-central-1.compute.internal bash[888]: 2017/11/14 15:10:29 line 1539: error: did not find expected key
Nov 14 15:10:29 ip-10-1-12-78.eu-central-1.compute.internal bash[888]: 2017/11/14 15:10:29 line 0: warning: incorrect type for "" (want struct)
Nov 14 15:10:29 …
```

Fix indentation

---

v_0_1_0/worker_template.go

fix for https://github.com/giantswarm/giantswarm/issues/2122
There is situation where the new worker is spawned but master still doesn't run the new `kube-proxy` as daemon set that will cause that worker is without proxy.
This hack puts `k8s-proxy` unit back but its disabled by default. If after 2 mins after the kubelet start there are no `kube-proxy` pod running on the machine it will start the old k8s-proxy via systemd.

backwards-compatibility-for-kube-proxy

---

v_0_1_0/master_template.go
v_0_1_0/worker_template.go

Towards https://github.com/giantswarm/giantswarm/issues/1482
We'll bring this back eventually running on kubernetes, but I thought i'd tidy it up as I was here anyway.

Removes old node-exporter service

---

v_0_1_0/worker_template.go

Removes kubeproxy unit and watcher added in #243 as it causes problems on AWS.
Clusters on AWS take longer to start due to nodes booting and ELBs. The timer means a second kube-proxy is created but the ingress ports are already bound so they fail.
Is this change needed for AWS? If not I'll add the units to kvm-operator so they can be embedded in the cloud config.

Remove kubeproxy unit

---

v_0_1_0/master_template.go

Due to multiple `ExecStart` instruction, the service was failing because the `chmod` was done before the `mkdir`
this PR fix the problem

fix master template

---

v2/cloudconfig.go
v2/cloudconfig_test.go
v2/fake_extension.go
v2/master_template.go
v2/operator.go
v2/operator_test.go
v2/worker_template.go

The CRD migration requires us to use the generated types of our CRD clients. There we have a new common ground which is used to render templates. Thus we need to introduce a new version of the templates in order to be able to use the new types. This here is just copy/paste of the existing templates. No changes are applied. I will provide another PR for the real changes. That way we see better what is going on. 
Note that I chose a simpler versioning since I think the folder naming how we had it was weird. We will not expose our internal versioning so it does not has to be semver. We can simply increment single numbers to distinguish different template versions.

copied v_0_1_0 package

---

v1_1/cloudconfig.go
v1_1/cloudconfig_test.go
v1_1/fake_extension.go
v1_1/master_template.go
v1_1/operator.go
v1_1/operator_test.go
v1_1/worker_template.go

We copy `v2` to get a version for KVM that has the generated client types but without the experimental encryption.

copied v2 package

---

v_3_0_0/master_template.go
v_3_0_0/types.go
v_3_0_0/worker_template.go

Towards https://github.com/giantswarm/giantswarm/issues/1384
This is to allow things like:
```
-v /var/lib/waagent/ManagedIdentity-Settings:/var/lib/waagent/ManagedIdentity-Settings:ro
```
Or
```
--cloud-config=/etc/kubernetes/config/azure.yaml
```
They are azure specific.

v_3_0_0: allow extra hyperkube options

---

v_3_0_0/master_template.go
v_3_0_0/types.go

Towards https://github.com/giantswarm/giantswarm/issues/1384
The goal here is to allow passing extra calico manifests for azure-operator.

v_3_0_0: allow extra manifests

---

v_3_0_0/types.go

This makes initialization outline nicer.
See https://github.com/giantswarm/azure-operator/pull/79/commits/b5e04aa7c59e2af3d6cd311f79350e185839cc0d

v_3_0_0: add fine hyperkube types

---

CHANGELOG.md
v_2_0_1/master_template.go

Enable legacy audit logging. (It was disabled in 1.8 by default)
Fix mounts for audit log
Extend audit log size.

V201 fix audit

---

CHANGELOG.md
v_3_0_0/master_template.go

- proper mounts
- add audit log policy (log all)
- allow to take max 3G for audit logs
Proper audit log policy should be done separately, probably as part of https://github.com/giantswarm/giantswarm/issues/1877

v_3_0_0. Fixes audit log.

---

CHANGELOG.md
v_3_1_1/master_template.go

This parameter is located in wrong section (https://www.freedesktop.org/software/systemd/man/systemd.unit.html)

Fix etcd3 service StartLimitIntervalSec location

---

v_3_1_1/master_template.go
v_3_1_1/types.go

Previous change broke possibility for templating api-server bind address. This feature is required for `azure-operator` and blocks release of the new bundle.

Fix api-server bind address

---

v_3_1_1/master_template.go
v_3_1_1/types.go

With selfhosted components, we need another way to add custom mounts. This is how I see we can do it. Naming is not that god, but for now I'm just testing stuff here: https://github.com/giantswarm/azure-operator/pull/122 . With this configuration I'm able to run k8s components as selfhosted. There are still some other issues, so this is only a part of a change

Add HostMount extension

---

CHANGELOG.md
v_3_1_1/master_template.go

Use ipip pinger, becase we are still seeing stuck IPIP tunnels
even with Calico 3.0.2
Initial Calico bug: https://github.com/projectcalico/calico/issues/1357

v_3_1_1: Added calico-ipip-pinger and remove WIP

---

v_3_2_1/master_template.go
v_3_2_1/worker_template.go

Towards: https://github.com/giantswarm/giantswarm/issues/2634

Protect kubernetes key pods from eviction

---

CHANGELOG.md
v_3_2_5/master_template.go

We manage this service by timer, so we don't want it to be started on boot. Starting it on boot causes race conditions sometimes, because systemd will start etcd3-defragmentation immediately after etcd3, so etcd3 was not be able to start.
similar to: https://github.com/giantswarm/giantnetes-terraform/pull/59

Disable etcd3-defragmentation service in favor timer

---

CHANGELOG.md
v_3_2_5/master_template.go

Finally we can remove ipip pinger, i've checked and guest clusters actually already have rule to allow ALL traffic (including protocol 4 - IPv4 encapsulation) between master and workers.

Remove calico ipip pinger

---

CHANGELOG.md
v_3_2_5/master_template.go
v_3_2_5/worker_template.go

fixes: https://github.com/giantswarm/giantswarm/issues/2913
In new docker `17.12.1` (in latest stable CoreOS):
- was completely removed flag `--disable-legacy-registry=true`
- removed support for `shared` mount mode, instead `rshared` should be used (details wtf it means [here](https://github.com/giantswarm/giantnetes-terraform/pull/56)).

Changes required for new docker

---

CHANGELOG.md
v_3_2_5/master_template.go

There was [regression](https://github.com/coredns/coredns/issues/1532) in CoreDNS that caused broken e2e conformance tests for DNS [here](https://github.com/giantswarm/giantnetes-terraform/pull/68#issuecomment-381061326).
Initial change: https://github.com/giantswarm/giantnetes-terraform/pull/72

v_3_2_5: Updated CoreDNS to 1.1.1

---

CHANGELOG.md
v_3_2_5/master_template.go

There were number of bugfixes from 3.0.2
https://docs.projectcalico.org/v3.0/releases/

v_3_2_5: updated Calico to 3.0.5

---

v_3_2_5/master_template.go
v_3_2_5/worker_template.go

`giantswarm` user for sso does not have public key to be configured during node provisioning

Check for empty public key

---

CHANGELOG.md
v_3_2_5/master_template.go

towards https://github.com/giantswarm/giantswarm/issues/2973
TLDR:
We reuse our CA and certs for aggregation API thus we need to allow at least for the known CNs (master and worker certs) which are the two templated domains I added so that aggregation API and services that use it do not log errors all the time (see PM)

add master/worker CNs to aggregator allowed names

---

CHANGELOG.md
v_3_2_5/master_template.go

This change disables unnecessary built-in SSL proxying.
Tested in `gauss`. SSL passthru still works fine.
With this change we still can use SSL passthru, because we have AWS ELB proxy protocol enabled. In case, of KVM/Azure we also need to have proxy protocol enabled in external load balancer. Enabling this flag in nginx-ingress-controller only makes sense if no external load balancer if used.
See my comment for details: https://github.com/kubernetes/ingress-nginx/issues/2354#issuecomment-382757307
Fixes: https://github.com/giantswarm/giantswarm/issues/2948

v_3_2_5: Disable SSL passthrough in nginx-ingress-controller

---

CHANGELOG.md
v_3_2_5/master_template.go
v_3_2_5/worker_template.go
v_3_2_6/master_template.go
v_3_2_6/worker_template.go

This is exception for already freezed 3.2.5 release.
Problem that it was broken for a while (from beginning?). We either can remove brackets `{}` to let systemd handle environment variable (still not clear why brackets break this) or remove explicit label setup completely. I've tested in kvm/azure/aws and kubelet properly detects hostname.
Fixes: https://github.com/giantswarm/giantswarm/issues/2999

v_3_2_5: Remove explicit hostname labeling

---

CHANGELOG.md
v_3_2_6/master_template.go

see https://kubernetes.io/docs/concepts/policy/pod-security-policy/#example-policies
this is so that privileged can be used for a more extended security context, in our docs we commend not to use this but to use a narrower one based on restricted psp.

sync privileged psp with upstream

---

README.md

Define versioning rules for k8scc taking into account feedback i got after trying to create patch release for aws-operator https://github.com/giantswarm/aws-operator/pull/921

Add versioning part to readme

---

CHANGELOG.md
v_3_3_0/master_template.go

Towards https://github.com/giantswarm/giantswarm/issues/1902
The component is hosted in https://github.com/giantswarm/kubernetes-kube-state-metrics/. It will be managed by chart-operator as part of the managed services story.

Remove kube-state-metrics

---

CHANGELOG.md
v_3_3_2/master_template.go
v_3_3_2/worker_template.go

Towards giantswarm/giantswarm/issues/3332
Downgrades K8s to 1.10.2 due to a regression with config maps. Also freezes v_3_3_2 so it can be used in AWS release 4.2.0.

v_3_3_2: downgrade Kubernetes to 1.10.2 and freeze

---

CHANGELOG.md
v_3_3_3/master_template.go
v_3_3_3/worker_template.go

Towards giantswarm/giantswarm/issues/3332
K8s 1.10.4 was released yesterday and has the configmap fix. Tested on gauss including verifying the configmap fix that was a regression in 1.10.3.
See https://github.com/giantswarm/giantswarm/issues/3332

v_3_3_3: Update hyperkube to 1.10.4

---

CHANGELOG.md
v_3_3_4/master_template.go
v_3_3_4/types.go

Towards giantswarm/giantswarm#1902
Allows disabling of Ingress Controller. This is so we can migrate it to chart-operator on Azure first.

Add parameter for disabling ingress controller

---

CHANGELOG.md
v_3_3_4/master_template.go
v_3_3_4/worker_template.go

towards https://github.com/giantswarm/giantswarm/issues/3386
Pulling hyperkube image for kubelet can take longer, and if it hits timeout systemd will terminate it and the process starts again so its take much more time to spin up.

increase kubelet start timeout

---

v_3_4_0/master_template.go

We are using original coreos/etcd instead of our retagged image. This change will allow us to use etcd on aliyun.

Use retagged etcd image

---

CHANGELOG.md
v_3_4_0/master_template.go

By default controller starts worker number equal to number of cores. Every worker consumes 45MB memory in stand-by, this causes OOM kills (for default limit 700MB) if core number >=16 (Big VMs).
Fixes: https://github.com/giantswarm/giantswarm/issues/3536

Use static worker count for nginx

---

CHANGELOG.md
v_3_4_0/master_template.go

add RBAC rules for the host cluster prometheus ( will be needed when we switch to specific certs per service, now we mostly use `api.xxx` certs but we will use `prometheus.xxx`)
RBAC rules copied from https://github.com/prometheus/prometheus/blob/master/documentation/examples/rbac-setup.yml

add rbac rules for prometheus

---

CHANGELOG.md
v_3_5_0/master_template.go

See https://github.com/giantswarm/kubernetes-nginx-ingress-controller/pull/23 from @marians. I'd like to keep the chart and the manifests here in sync until the AWS and KVM migration is complete.

Disable HSTS headers for Ingress Controller

---

CHANGELOG.md
v_3_6_0/master_template.go
v_3_6_0/worker_template.go

Part of: https://github.com/giantswarm/giantswarm/issues/3922
also move to single manifest like we do in "control plane" cluster. this allows to copy-paste official upstream manifests.

Upgrade calico to 3.2.0

---

v_3_6_0/master_template.go

Closes https://github.com/giantswarm/giantswarm/issues/4242
The extra dash was causing:
```
Sep 24 09:22:38 ip-10-1-6-27.eu-central-1.compute.internal k8s-addons[2131]: error: the path "/srv/kube-proxy-ds.yamlMANIFESTS=" does not exist
Sep 24 09:22:38 ip-10-1-6-27.eu-central-1.compute.internal k8s-addons[2131]: failed to apply /srv/kube-proxy-ds.yamlMANIFESTS=, retrying in 5 sec
```

fix coredns manifest removal

---

v_4_0_0/master_template.go

Removes outdated TPR (deprecated, no object is created now from it) and fixes coredns manifest removal (was missing in #421 to apply it to v_4_0_0 too).

Remove network-policy TPR

---

v_4_0_0/master_template.go
v_4_0_0/types.go
v_4_0_0/worker_template.go

Towards https://github.com/giantswarm/giantswarm/issues/2816
cloudinit used schema "base64_gzip" for `encoding` field.
ignition uses `base64` in data schema uri and has only `gzip` for compression. So, operators, which are rendering ignition, will use boolean value to enable compression

Replace cloudinit encoding with ignition compression

---

CHANGELOG.md
v_3_6_2/master_template.go
v_4_0_0/files/k8s-resource/calico-all.yaml

Part of: https://github.com/giantswarm/giantswarm/issues/4159

Add resource limits for calico and update to 3.2.3

---

CHANGELOG.md
v_3_6_2/master_template.go
v_4_0_0/files/manifests/k8s-api-server.yaml

in 4.0.0 change https://github.com/giantswarm/k8scloudconfig/pull/420 was lost also backport to 3.6.2 (which will be current WIP in operators)

Bring back lost change in 4.0.0 and backport to 3.6.2

---

CHANGELOG.md
v_3_6_2/master_template.go
v_4_0_0/files/k8s-resource/calico-all.yaml

Part of: https://github.com/giantswarm/giantswarm/issues/4159
Now we get QoS policy guaranteed.

4.0.0 and 3.6.2: Add resource limits to install-cni.

---

v_3_7_0/master_template.go

Should fix this error 
```
file.go:187] Can't process manifest file "/etc/kubernetes/manifests/audit-policy.yml": /etc/kubernetes/manifests/audit-policy.yml:  couldn't parse as pod(no kind "Policy" is registered for version "audit.k8s.io/v1beta1" in scheme "k8s.io/kubernetes/pkg/api/legacyscheme/scheme.go:29"), please check config file
```

update audit policy api version

---

CHANGELOG.md
v_3_7_0/worker_template.go

we don't have any pod manifests on workers. 
kubelet on workers logs:
```
Unable to read config path "/etc/kubernetes/manifests": path does not exist, ignoring
```

remove static pod path from worker

---

CHANGELOG.md
v_3_7_0/master_template.go
v_3_7_0/worker_template.go

this port was used by heapster before. heapster got replaced so there is
no need to keep the port.

remove readonly port from kubelet

---

v_3_7_1/master_template.go

during an upgrade calico was not coming up. so the proxy stayed at 1.10
although the cluster was already 1.12. so since the proxy is not
dependent on calico we can just install it before we are installing and
waiting for calico.

install kube-proxy in master before calico

---

v_3_7_2/cloudconfig.go
v_3_7_2/cloudconfig_test.go
v_3_7_2/common_template_test.go
v_3_7_2/error.go
v_3_7_2/master_template.go
v_3_7_2/master_template_test.go
v_3_7_2/render_asset_content.go
v_3_7_2/render_asset_content_test.go
v_3_7_2/types.go
v_3_7_2/worker_template.go
v_3_7_2/worker_template_test.go

calico is a bit picky about the etcd connection and the number of
(healthy) nodes in the cluster. so this makes sure that dns to etcd is
wired properly and that the old master is removed before calico is
(re-)started.

add 3.7.2 to fix calico startup during upgrade

---

v_4_0_0/master_template.go

The ugliest workaround you'll find today on the internet. 
But this thing just blocks me from moving with ignition and k8s 1.13. 
Upstream issue: https://github.com/kubernetes/kubernetes/issues/71078
Shortly - kubelet loses connection in the middle of booting and can't restore it. Happens only to master. Restarting container helps.

Restart master kubelet after running core components

---

CHANGELOG.md
v_3_7_4/master_template.go
v_4_0_0/files/k8s-resource/calico-all.yaml

related: https://github.com/giantswarm/giantswarm/issues/4113

Remove nodename_file_optional from calico configmap

---

v_4_0_0/files/manifests/k8s-api-server.yaml

If we don't specify this - api-server will listen on 8080 without auth. It was there before ignition. Just somehow deleted it by mistake during migration

Bring back missing apiserver config

---

v_4_0_0/worker_template.go

We were wondering why there are no worker role labels. The change here is pretty simple. What could possibly go wrong? I checked some upstream issues and only found concerns of master role labels being applied in an uncontrolled way. So we should be safe. Further I am not sure why we should have two different labels for that.

adds worker role labels

---

CHANGELOG.md
LICENSE
v_4_0_0/master_template.go

Sometimes on overloaded master etcd-defragmentation can take a little longer and the default timeout can be very low.
Just adjusting limits so we see less failed units ( and have more reliable defragmentation)

increase-timeout-for-etcd-defrag

---

CHANGELOG.md
v_4_1_0/files/policies/audit-policy.yaml

As mentioned by @webwurst during the daily planning and also in here https://github.com/giantswarm/giantswarm/issues/5323, we could tweak the audit policy to collect fewer logs. Like the first run, this is merely a copy/paste of the rules recommended from Google (https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/gci/configure-helper.sh#L783) to how to decrease the audit logs considerably on those resources that create high-volume of logs and low-risk. I've put all, but we can discuss here if we are okay with all of them or we want to change/tune them according to our needs.
This also will help us in having fewer logs around (even when we'll collect logs in separate disks)

Decrease audit logs

---

v_4_1_0/files/config/kube-proxy.yaml

ipvs is still experimental and with 1.12.x clusters we are still having
issues with it. so for now we go back to 'iptables'

switch kube-proxy back to iptables

---

v_4_3_0/files/k8s-resource/calico-all.yaml
v_4_3_0/files/k8s-resource/kube-proxy-ds.yaml

Towards: https://github.com/giantswarm/giantswarm/issues/5744
We encountered an issue where `kube-proxy` was not scheduled on some node due to them having the following taint:
```
taints:
- effect: NoSchedule
key: NodeWithImpairedVolumes
value: "true"
```
Therefore we need to have `kube-proxy` tolerating every `NoSchedule` taint and not only the ones with `key: node-role.kubernetes.io/master`.
How about aligning toleration with calico and adding toleration for `CriticalAddonsOnly` and `NoExecute` also ?
https://github.com/giantswarm/k8scloudconfig/blob/80b22e313bd60f651c8f24456e366931ef2a347d/v_4_3_0/files/k8s-resource/calico-all.yaml#L120-L128

Allow kube-proxy to tolerate all NoSchedule taint

---

CHANGELOG.md

Towards: https://github.com/giantswarm/giantswarm/issues/5744
Forgot to update changelog earlier.
Update changelog about taint toleration for kube-proxy and calico.

Update changelog: kube-proxy and calico taint toleration

---

CHANGELOG.md

Copy and replace PRs are already done. This adds a new WIP version as `4.3.0` is used in k8s 1.14.1.

Add new WIP 4.4.0

---

CHANGELOG.md
v_4_3_0/files/k8s-resource/calico-all.yaml
v_4_4_0/files/k8s-resource/calico-all.yaml

Expose Felix metrics in calico, so we or customers can use Prometheus to scrape Felix state.

Add felix metric server for expose calico metrics

---

v_4_4_0/files/conf/hardening.conf

Towards https://github.com/giantswarm/giantswarm/issues/5983
This will allow to drop initContainer with sysctl, which requires psp to allow privileged containers

Move ic performance improvements into os provisioning

---

v_4_4_0/master_template.go
v_4_4_0/types.go
v_4_4_0/worker_template.go

This PR aligns Owner structure with ignition spec and allows to use `id` of the group instead of name. Required for this https://github.com/giantswarm/azure-operator/pull/519

Use new owner structure

---

v_4_4_0/files/conf/hardening.conf

This article actually mentions that this setting in a file is set without `"`:
https://www.cyberciti.biz/tips/linux-increase-outgoing-network-sockets-range.html
I tested it and this fixes the following failure:
```
Jun 12 13:12:54 localhost systemd-sysctl[1006]: Couldn't write '"1024 65535"' to 'net/ipv4/ip_local_port_range': Invalid argument
```

Fix hardening formatting

---

v_4_4_0/files/conf/hardening.conf
v_4_4_0/files/conf/sshd_config

Towards https://github.com/giantswarm/giantswarm/issues/6070
Same thing applied for CP.
Notice here that the forwarding is disabled both for workers and masters.
It is not needed

Harden SSH

---

v_4_5_0/master_template.go
v_4_5_0/worker_template.go

In current WIP kvm releases, I see this issue
```
E0707 21:04:18.352245    1540 remote_runtime.go:132] StopPodSandbox "7f74e9f13ce04561def21b699e4f0c5012e69d0bae3cc558059e15936b4eb681" from runtime service failed: rpc error
: code = Unknown desc = NetworkPlugin cni failed to teardown pod "tiller-deploy-54494c4fb6-kzsqq_giantswarm" network: neither iptables nor ip6tables usable                  
E0707 21:04:18.353119    1540 kuberuntime_manager.go:846] Failed to stop sandbox {"docker" "7f74e9f13ce04561def21b699e4f0c5012e69d0bae3cc558059e15936b4eb681"}               
E0707 21:04:18.356706    1540 kuberuntime_manager.go:641] killPodWithSyncResult failed: failed to "KillPodSandbox" for "8a70c9ae-a0f9-11e9-95c7-deadbeba91dc" with KillPodSan
dboxError: "rpc error: code = Unknown desc = …
```

Fix kubelet PATH

---

v_4_5_0/master_template.go
v_4_5_0/worker_template.go
v_4_6_0/master_template.go
v_4_6_0/worker_template.go

This is related to issue with node-exporter, where it mounts volumes as user `1000`, but on some nodes, this user has a different ID. So with this, we will explicitly create it with ID 1000.
After all clusters will be upgraded, we will remove a user from here https://github.com/giantswarm/installations/blob/master/default-draughtsman-configmap-values.yaml#L87

Make sure GiantSwarm user has id 1000

---

CHANGELOG.md
v_4_5_0/files/k8s-resource/priority_classes.yaml
v_4_6_0/files/k8s-resource/priority_classes.yaml

Towards https://github.com/giantswarm/giantswarm/issues/6405
Priority classes graduated to stable in 1.14. So this gets the manifest sorted.

Use v1 stable for priority class

---

v_4_2_0/files/conf/wait-for-domains
v_4_2_0/master_template.go
v_4_3_0/files/conf/wait-for-domains
v_4_3_0/master_template.go
v_4_4_0/files/conf/wait-for-domains
v_4_4_0/master_template.go
v_4_5_0/files/conf/wait-for-domains
v_4_5_0/master_template.go
v_4_6_0/files/conf/wait-for-domains
v_4_6_0/master_template.go

this change cames out of the test we have here https://github.com/giantswarm/aws-operator/pull/1752 and the goal was to improve AWS e2e test as they were often flaky
One of the findings was that sometimes the DNS in AWS ins unreliable, it can resolve local domains but timeouts on global domains, that bring some confusion and failures
When k8s-setup-network-env failed than etcd3 failed too because of failed dependency and never started again. Usually, the k8s-setup-network-env self-healed in time but etcd3 was dead.  Setting `Wants` instead of `Require` causes that etcd3 will start and fail but the restart policy will keep th etcd3 restating until it can start and that helped in the AWS e2e a lot.
another change is adding an external domain to `wait-for-domain` to ensure we can resolve …

improve etcd retry policy and wait for domains

---

CHANGELOG.md
v_4_6_0/master_template.go
v_4_6_0/worker_template.go

Full `PATH` is set since `$PATH` can't be used in systemd unit files. I took the path from a running instance.
The rbd tool wants to run `docker` and for this mounting of `/usr/bin/docker` `/run/metadata/torcx` and `/run/torcx/` on CoreOS.
I don't know about using `ro` `rw` or `rshared` on these, so please advise.

Make rbd usable via Kubelet

---

CHANGELOG.md
v_4_6_0/master_template.go
v_4_6_0/worker_template.go

This is required for cert-exporter to be able to read certificates while running as user `1000`

Change certs owner

---

CHANGELOG.md
v_4_6_0/cloudconfig.go
v_4_6_0/master_template.go
v_4_6_0/types.go
v_4_6_0/worker_template.go

Towards https://github.com/giantswarm/giantswarm/issues/6367
Makes `--image-pull-progress-deadline` configurable for kubelets with a default of 1 minute. We will increase this to 10 minutes for tenant clusters in AWS China regions. This mitigates the extremely slow image pulls we see there which are outside of our control.
This happened in control plane clusters a long time ago and we decided to implement for tenants as well.
> --image-pull-progress-deadline duration
>  If no pulling progress is made before this deadline, the image pulling will be cancelled. (default 1m0s)
https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/

Make image pull progress deadline configurable for kubelets

---

CHANGELOG.md
v_4_6_0/files/config/kubelet-master.yaml.tmpl
v_4_6_0/files/config/kubelet-worker.yaml.tmpl
v_4_6_0/master_template.go
v_4_6_0/worker_template.go

Towards https://github.com/giantswarm/giantswarm/issues/6270
- `docker` daemon moved from root cgroup into kubereserved. 
- `kubelet` and `etcd` systemd services moved under `kubereserved` cgroup. This is not that important, as containers itself are placed into cgroups by docker daemon configuration. But this change was done to keep related things better structured
- with `--parent-cgroup` configuration, all the containers, started by docker without k8s context (e.g. kubelet/etcd) are started under `kubereserved` cgroup.
- `SystemReserved` configuration explicitly points to `system` cgroup and has explicitly reserved resources.
- `Kubereserved` configuration has explicitly reserved resources.
This means, that there will be less allocatable resources for nodes:
```
[Allocatable] = [Node …
```

Custom cgroup structure

---

CHANGELOG.md
v_4_7_0/cloudconfig.go
v_4_7_0/cloudconfig_test.go
v_4_7_0/common_template_test.go
v_4_7_0/error.go
v_4_7_0/filemanager.go
v_4_7_0/filemanager_test.go
v_4_7_0/master_template.go
v_4_7_0/master_template_test.go
v_4_7_0/render_asset_content.go
v_4_7_0/render_asset_content_test.go
v_4_7_0/types.go
v_4_7_0/worker_template.go
v_4_7_0/worker_template_test.go

We use `v_4_6_0` in an active azure release now. See here:
https://github.com/giantswarm/azure-operator/blob/d46da3a0418cfbd2d107f574bc470c2d4b532fbd/service/controller/v9/cloudconfig/worker_template.go#L8
I create a new folder for k8scc to not accidentally disturb production of active releases with WIP merges.

v_4_7_0 imports and changelog

---

CHANGELOG.md
v_4_9_0/files/manifests/k8s-api-healthz.yaml
v_4_9_0/master_template.go

add healthz microservice also to TC
for now, it's just going to sit there, but we can later enable settings for all providers
I need this for further KVM without flannel testing
for https://github.com/giantswarm/giantswarm/issues/7151
We have this on cloud CPs and it works nicely. Also it get rid of the annoying spam error message in API logs about broken TLS connection.

add-k8s-api-healthz-service

---

CHANGELOG.md
v_4_9_0/files/k8s-resource/calico-all.yaml

Towards https://github.com/giantswarm/giantswarm/issues/7022
For the new upcoming release, we'll remove Calico Node limits and let it burst. We have already in place an alert that notify us in case the memory used is equals to the one requested.

Remove calico limits

---

CHANGELOG.md
v_5_0_0/files/conf/hardening.conf
v_5_0_0/files/config/kube-proxy.yaml

After our discussion we'll rollback ipvs in other GS release and rely to fix network errors (iptables restore) on the upstream fix landing in k8s 1.16 coming with the upcoming GS release

Revert IPVS to iptables

---

CHANGELOG.md
v_5_0_0/files/k8s-resource/calico-all.yaml

Towards https://github.com/giantswarm/giantswarm/issues/7939
Assign `system-node-critical` to `calico-node` to have a higher priority over all other resources in a node and avoid to be evicted.

Change Priority Class for calico-node

---

CHANGELOG.md
v_5_0_0/files/conf/wait-for-domains
v_5_0_0/files/manifests/k8s-api-healthz.yaml

Towards https://github.com/giantswarm/giantswarm/issues/7773
Fixes last 2 instances of `quay.io` hardcoding in `v_5_0_0`. This is so we use the retagged images in China.

Use registry domain for k8s-api-healthz and wait for domains script.

---

v_5_0_0/master_template.go
v_5_0_0/worker_template.go

This makes the labeling service more resistant to the kubelet having a rough start which seems to happen on `azure`. Now all nodes get labeled correctly:
```
k get nodes   
NAME                  STATUS   ROLES    AGE     VERSION
9g6ci-master-000000   Ready    master   7m56s   v1.16.3
9g6ci-worker-000000   Ready    worker   2m      v1.16.3
9g6ci-worker-000001   Ready    worker   115s    v1.16.3
9g6ci-worker-000002   Ready    worker   114s    v1.16.3
```

Harden label service against kubelet flaps

---

v_5_0_0/master_template.go

cluster-autoscaler has a toleration on `node-role.kubernetes.io/master`. Since this taint/toleration isn't actually related to the 1.16 role label changes, I am reverting `--register-with-taints` to its original value (changed here https://github.com/giantswarm/k8scloudconfig/commit/d462f8eadb3adacc49195758d47a47de57c96420#diff-7dc3f634c8bce58559a71d4cd5203f7fL293).

Revert master role taint

---

v_5_0_0/files/k8s-resource/calico-all.yaml

`calico-kube-controllers` doesn't get scheduled in release 11.0 clusters because I forgot to change its toleration in https://github.com/giantswarm/k8scloudconfig/pull/624. This PR corrects that.

Revert master role taint for calico-kube-controllers

---

v_5_0_0/files/conf/install-debug-tools

We see these units fail quite recently. This should help with failures in the unit.
This does not affect much, but having the failed unit causes alerts.

Add longer timeout and retries for wget operation in debug-tools

---

v_5_1_0/master_template.go

Script is still there to install manually - just not automatically everywhere.

Remove debug tools systemd unit

---

CHANGELOG.md
v_5_1_0/files/conf/k8s-addons
v_5_1_0/master_template.go
v_5_1_0/worker_template.go

Starting from release v_5_0_0 e.g. node labels were set by separate systemd
unit with kubectl and that must match running hostname with k8s node name.
That matching is case sensitive and since Azure sets hostname with uppercase
letters in Base36 encoding, the hostname must be convered to lowercase in order
to match k8s node name.

Lowercase $(hostname) when matching k8s node name with it

---

CHANGELOG.md
v_5_1_0/files/config/kubelet-master.yaml.tmpl
v_5_1_0/files/config/kubelet-worker.yaml.tmpl

This reverts commit 0a6035168fd670351f1204ad3444ecf67b681cd0.
According to @sslavic's findings this change does not help to fix https://github.com/giantswarm/giantswarm/issues/8361 so reverting

Revert "Increase kubelet hard memory eviction (#635)"

---

CHANGELOG.md
README.md
v_5_2_0/files/conf/hardening.conf

I messed up rebasing the last PR somehow. Here is the fix for https://github.com/giantswarm/giantswarm/issues/8798, this replaces https://github.com/giantswarm/k8scloudconfig/pull/638

Add reserved ephemeral port range to avoid conflicts with kube-apiserver

---

CHANGELOG.md
v_5_2_0/master_template.go
v_5_2_0/worker_template.go

We have the issue in aws, where reboot doesn't reprovision a node. It is not consistent behavior. 
This PR should fix it

First boot always

---

CHANGELOG.md

Fixing changelog [for v5.1.1](https://github.com/giantswarm/k8scloudconfig/pull/644).

v5.1.1: changelog

---

v_6_0_0/release.go
v_6_0_0/types.go

Wiring to pass container image version for k8s-network-setup was missing but
it's required. Therefore add it.

Add missing wiring for k8s-network-setup container image

---

CHANGELOG.md
v_4_9_1/files/k8s-resource/calico-all.yaml

Cherry pick of #677 for dep-based operators. Will be released as 0.1.1.

legacy: Remove init limits for calico (#677)

---

v_6_0_0/release.go
v_6_0_0/types.go

Legacy port of #668.
Wiring to pass container image version for k8s-network-setup was missing but
it's required. Therefore add it.

legacy: Add missing wiring for k8s-network-setup container image (#668)

---

README.md

Following from https://github.com/giantswarm/k8scloudconfig/pull/682
Since we will have a long-lived branch `legacy` until active provider operators are all updated to use go modules, these branches should be documented to help decide where to target future changes.

Document branches in README.md

---

v_6_0_0/files/k8s-resource/kube-proxy-ds.yaml

In an effort to have homogeneous labels, I removed this one as it is not used.

Remove unused kube-proxy component label

---

CHANGELOG.md
v_6_0_0/files/manifests/k8s-controller-manager.yaml
v_6_0_0/files/manifests/k8s-scheduler.yaml

Towards https://github.com/giantswarm/giantswarm/issues/4813
Removes the debug profiling endpoint at /debug/pprof for Controller Manager and Scheduler

Remove profiling from Controller Manager and Scheduler

---

CHANGELOG.md
v_6_0_0/files/conf/hardening.conf

During hardening epic last year, these settings got moved from nginx init container to be set on host. Only recently we've uncovered this didn't actually work. For more info see https://github.com/giantswarm/nginx-ingress-controller-app/pull/55#issue-402580553
Init container got reinstated via https://github.com/giantswarm/nginx-ingress-controller-app/pull/61
Assumption is these settings are not needed by anything else and can be removed from the host.

Remove IC performance improvements from OS provisioning

---

CHANGELOG.md
files/k8s-resource/calico-all.yaml
files/k8s-resource/calico-policy-only.yaml
files/k8s-resource/kube-proxy-ds.yaml

I discovered during testing that the [recent label changes](https://github.com/giantswarm/k8scloudconfig/pull/695) cause k8s-addons to fail because the manifests are applied using `kubectl apply -f <file>` and `matchLabels` can't be changed on an existing deployment. We don't want to delete these deployments so I'm just reverting the changes.

Fix deployment labels

---

files/manifests/k8s-api-server.yaml
pkg/template/cloudconfig.go
pkg/template/master_template.go
pkg/template/types.go

For HA masters story
non-HA masters should stay the same and the only change is how the etcd cluster is bootstrapped when the HA masters flag is TRUE.

'ha-masters-flattened'

---

files/conf/calicoctl.cfg
files/conf/etcd-alias
files/conf/k8s-addons
files/k8s-resource/calico-all.yaml
files/manifests/k8s-api-healthz.yaml
files/manifests/k8s-api-server.yaml
pkg/template/cloudconfig.go
pkg/template/cloudconfig_test.go
pkg/template/master_template.go
pkg/template/types.go

included Thomas PR as well https://github.com/giantswarm/k8scloudconfig/pull/717
The etcd flag changes are to fix this error on single master clusters `May 13 22:45:26 master-h6s3z-9c95bc6d9-st2jl docker[16688]: 2020-05-13 22:45:26.705707 C | etcdmain: --initial-cluster has etcd0=https://127.0.0.1:2380 but missing from --initial-advertise-peer-urls=https://etcd.<redacted>.kvm.gigantic.io:2380 ("https://<redacted>:2380"(resolved from "https://etcd.<redacted>.kvm.gigantic.io:2380") != "https://127.0.0.1:2380"(resolved from "https://127.0.0.1:2380"))`

add nodeName to the params

---

CHANGELOG.md
pkg/template/cloudconfig.go

After a little discussion, @calvix and I decided to drop the index suffix from the etcd node name for single master clusters. `etcd1` becomes `etcd`. This helps us with backwards compatibility in other operators where we currently create DNS records like `etcd.<domain>`.

Drop index suffix for non-HA etcd

---

CHANGELOG.md

Releasing this for the upcoming kvm-operator release with 1.17 support. @giantswarm/team-firecracker-pe and @giantswarm/team-celestial once you update operators to use this version, the 12.0.0 release with Kubernetes 1.17 should simply require changing the Kubernetes version in release `components` and 1.16 should continue to work like normal.

Release v6.2.0

---

CHANGELOG.md
files/k8s-resource/calico-all.yaml
files/k8s-resource/calico-policy-only.yaml

This is necessary for calico 3.14 - otherwise `calico node` simply crashloops. Upstream code that causes this:
https://github.com/projectcalico/node/blob/b1dc3c17492a763676471f7e5c532331971a4034/pkg/startup/startup.go#L138-L150

Make calico 3.14 compliant

---

files/conf/k8s-addons

This old part of code is removing the other master nodes in case of node reboot. We don't need it for HA masters and AWS cloud provider should anyway clean old non-existing nodes.

dont-delete-master-nodes-on-HA

---

CHANGELOG.md

- Add `bird-live` flag to calico node liveness probe.
- RBAC permissions allowing calico node to get configmaps.
- Parameter to disable deletion of master nodes for HA masters.

Release v6.2.1

---

CHANGELOG.md
pkg/template/cloudconfig.go

This library now checks the passed in kubernetes version to determine which binaries should be copied out of the `hyperkube` image in the `k8s-extract` service. When I set this to 1.17, this led previously-working operators to stop working when upgrading to k8scloudconfig v6.2.0+ because it wasn't necessary to pass in kubernetes version. To get the 1.17 compatibility, the version needs to be passed in (implemented in AWS and KVM already).

Fix regression in kubelet installation systemd unit

---

pkg/template/cloudconfig.go
pkg/template/master_template.go
pkg/template/types.go

Another annoying change for the HA masters ( and hopefully last)
This is trying to solve an issue when we upgrade an etcd cluster from 1 to 3 nodes. In the current scenario, there is an issue that the first node is already bootstrapped and should serve as a source of truth for the two others. Unfortunately, with `new` flag they will create a separate working cluster and now there is a problem that they will respond healthy to the LBs and we practically have two k8s clusters running with separate data.
Setting the initial state to `existing` will prevent etcd from starting on the two other nodes and the migration process can help the other two nodes to join the cluster. 
maybe there are other ways how to disable etcd but this seems to be causing the least harm to any other cases.
In case …

set-initial-cluster-state

---

CHANGELOG.md
files/k8s-resource/calico-policy-only.yaml

enable metrics endpoint for calico policy only
move calico-policy only manifest to the  new image schema
remove typha deployment from calico-policy only - that is not needed, nto sure why its in the offcicial manifest
towards https://github.com/giantswarm/giantswarm/issues/11336

enable-calico-metrics-for-policy-only

---

CHANGELOG.md
files/config/kubelet-worker.yaml.tmpl

I'm testing rolling upgrades on Azure instances. For this, I need a health check endpoint so Azure can tell whether or not an instance is healthy. We thought using the kubelet health endpoint may be a good idea.
Azure makes requests to this endpoint using `localhost`, but we our current configuration we are binding the health endpoint just to the private IP address. With this PR, I'm binding to all IPv4 addresses so we can use both `localhost` and the private IP address.

Expose kubelet health check endpoint

---

CHANGELOG.md
files/conf/k8s-addons
files/config/kube-proxy.yaml
files/k8s-resource/calico-policy-only.yaml
pkg/template/cloudconfig.go
pkg/template/master_template.go
pkg/template/types.go

Towards: https://github.com/giantswarm/giantswarm/issues/11307
The goal of this PR is to upgrade `calico` to the latest release and to avoid having a separate calico manifest between AWS and Azure.

Calico unify

---

CHANGELOG.md
files/manifests/k8s-scheduler.yaml

The feature gate is a little bit cryptic but we disabled it to set custom PV node limits, as when the feature gate is enabled they will use some magic method to calculate the PV limit which is wrong. But unfortunately from  k8s version 1.17 the feature gate cannot be disabled.
There is nothing we can do atm, the customer is aware as well as SEs, the only solution is to move to CSI storage manager for EBS where limits can be applied again.

remove-pv-limit-aws

---

CHANGELOG.md
pkg/template/master_template.go

etcd 3.4.10 needs 0700 permission on the data dir
https://github.com/etcd-io/etcd/blob/master/CHANGELOG-3.4.md
chmod is the only way as we need to ensure older clusters will have this fixed as well.

set-etcd-data-dir-permissions-to-0700

---

CHANGELOG.md
files/conf/setup-kubelet-environment

According to the number we have from our conformance tests we need to adjust the number of hostnetwork pods on worker again
Pods with HostNetwork on the worker node:
aws-node-cxzz7 
calico-node-g5nz6 
cert-exporter-498x7 
kiam-agent-qkld4 
kube-proxy-zt67p 
node-exporter-n66tv

Fix: wrong max pod size for instance-types

---

CHANGELOG.md
pkg/template/master_template.go

This PR changes the etcd3.service systemd unit in order to use environment variables for some of the configuration options.
This makes it easier to use different approaches in the ETCD cluster initialization (that might be required by different cloud providers).
The default value of the environment variable is the same that was previously hardcoded and that should make this PR a drop-in replacement without side effects.

Expose etcd variables

---

CHANGELOG.md
files/conf/etcd-alias

The `etcdctl` alias has a reference to some TLS certificate files that are not available any more in our tenant clusters.
This PR changes those references to an existing file to restore the etcdctl feature.

Fix etcdctl alias

---

CHANGELOG.md
files/conf/etcd-alias
pkg/template/master_template.go

This PR backports changes from merged PRs #785 and #786 from the v8 to the v7 version of k8scc.
Needed to have those features in k8s 1.17 as well.

Backported ETCD related changes from v8 to v7

---

CHANGELOG.md
files/k8s-resource/calico-policy-only.yaml

This will be used in aws-operator release 11 and 12

Disable cni binaries

---

CHANGELOG.md
files/k8s-resource/calico-policy-only.yaml

The CNI running on a K8S should be in charge of installing it's own CNI binaries (portmap, bridge...)
Currently Calico and AWS CNI where fighting to setup this files:
https://github.com/giantswarm/giantswarm/issues/11077#issuecomment-685457567
And were also causing problems as nodes were being marked as Ready when AWS CNI was not even able to boot:
https://github.com/giantswarm/giantswarm/issues/13086
@whites11 not sure if this file is also being used in Azure, would this change still be fine?

Remove init container that installs CNI binaries

---

CHANGELOG.md
pkg/template/master_template.go
pkg/template/worker_template.go

Set root user for k8s-kubelet explicitly (v7)

---

CHANGELOG.md
pkg/template/master_template.go
pkg/template/worker_template.go

When upgrading a node so that the node identity doesn't change, old
labels need to be overwritten in order to become effective. Therefore
those must be applied in `k8s-label-node` unit.

Set configurable node labels in k8s-label-node unit

---

CHANGELOG.md
files/conf/setup-kubelet-environment

towards https://github.com/giantswarm/releases/pull/489/files#diff-0558904bd7b9ba9c4978a85be9be05734a316391b7e871a1a6045c461bcafb7cR74-R79
cert-expoter `v1.3.0` is no longer running on hostnetwork so removing it from the numbers to calculate  pod limit.
This is for AWS Only

aws-decrease-hostnetwork-pods-count

---

CHANGELOG.md
files/conf/k8s-addons
files/k8s-resource/calico-policy-only.yaml

I found during testing that `kubectl wait` has surprising behavior when using `wait` with a pod label selector. Rather than timing out after the specified timeout, it waits for the timeout for each matching pod in sequence. When Calico is not immediately ready (common during cluster creation), this causes us to wait for 40 minutes (10 * # of nodes) rather than the expected 10. I am adjusting the existing code to wait for only one minute and wrapped it with a loop so we can continue with cluster initialization more quickly.

Shorten calico-node and aws-node wait timeout and add retry

---

CHANGELOG.md
files/config/scheduler.yaml
go.mod
pkg/key/key.go
pkg/template/cloudconfig.go
pkg/template/cloudconfig_test.go
pkg/template/validation.go
pkg/template/validation_test.go

v1alpha1 is no longer supported in Kubernetes 1.19. We will need to determine if this is backwards compatible with <=1.18 before releasing.
Based on https://kubernetes.io/docs/reference/scheduling/config/
Towards https://github.com/giantswarm/roadmap/issues/247#issuecomment-741343638

update scheduler config version

---

pkg/template/release.go

Following from https://github.com/giantswarm/retagger/pull/516 We have certs in the upstream apiserver image so we don't need a custom suffix.

Drop apiserver image suffix

---

CHANGELOG.md
files/manifests/k8s-api-server.yaml

Towards https://github.com/giantswarm/giantswarm/issues/3398
Explicitly set the API server request timeout to 1 minute. This is the default value.

Set api-server request timeout

---

.circleci/config.yml
CHANGELOG.md
files/k8s-resource/calico-crds.yaml

When upgrading to k8s 1.19 I noticed that k8s-addons constantly retries to apply Calico CRD's.
This needs to be fixed by dropping the bgppeer KeepOriginalNextHop default field.
It has been already fixed in upstream: https://github.com/projectcalico/libcalico-go/pull/1353
https://github.com/giantswarm/giantswarm/issues/15878

Fix Calico CRDs

---

CHANGELOG.md
files/manifests/k8s-api-server.yaml

This fixes sonobuoys conformance test failure:
```
Failed tests:
[sig-auth] ServiceAccounts ServiceAccountIssuerDiscovery should support OIDC discovery of service account issuer [Conformance]
```
related to: https://github.com/giantswarm/giantswarm/issues/18215
---
Please see the following link for some more info.
https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-issuer-discovery

Set service-account-jwks-uri value

---

CHANGELOG.md
files/manifests/k8s-controller-manager.yaml

---
InTreePluginAWSUnregister was only introduced in k8s 1.21. This change is to allow k8scloudconfig to still work on older versions by only setting the flag if set true,

only add k8s controller flag if set to true

---

CHANGELOG.md
files/k8s-resource/calico-all.yaml

Fixing the following error in `calico-kube-controllers`:
```
E0803 03:06:45.223634       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.0-rc.0/tools/cache/reflector.go:167: Failed to watch *v1.NetworkPolicy: failed to list *v1.NetworkPolicy: networkpolicies.networking.k8s.io is forbidden: User "system:serviceaccount:kube-system:calico-kube-controllers" cannot list resource "networkpolicies" in API group "networking.k8s.io" at the cluster scope
```

Calico service account

---

CHANGELOG.md
pkg/template/master_template.go
pkg/template/worker_template.go

Towards: https://github.com/giantswarm/giantswarm/issues/20805
RPCbind (triggered by rpc-statd) is needed for NFS v3.
Azure and AWS do not use it (they use v4) and there is an open port that some customers don't like.
This PR disables rpc-statd for non-kvm clusters.

Remove `rpc-statd.service` dependency on `kubelet.service` on `AWS` and `Azure`.

---

CHANGELOG.md
files/k8s-resource/calico-all.yaml

Towards https://github.com/giantswarm/giantswarm/issues/20918
Cherry-picked from #999 to `release-v10.16.x`

Fix `calico-kube-controllers` permissions for `networkpolicies`

---

CHANGELOG.md
pkg/template/master_template.go

It does not have a negative impact,  the problem is that once the DB gets over the default 2GB the DB is locked and you cannot do anything until you increase the DB size or delete data and then disarm the alarm

increase-db-max-size

---

CHANGELOG.md
files/conf/kube-proxy-vpa
pkg/template/master_template.go

Towards: https://github.com/giantswarm/giantswarm/issues/21494
This PR adds a new systemd unit to master nodes that runs after `k8s-addons` and waits until `verticalpodautoscaler` CR exists before it creates the VPA for kube-proxy.
Hacky solution maybe, but I tested it and it works just fine.

Kube proxy vpa service

---

CHANGELOG.md
files/manifests/k8s-api-server.yaml
pkg/template/types.go

Issue: https://github.com/giantswarm/giantswarm/issues/21736
TL;DR 
Key files for new IRSA service account which signs JWT need to be after older service account key files.

Add extra sa key args for irsa

---

CHANGELOG.md
files/manifests/k8s-api-server.yaml
pkg/template/master_template.go
pkg/template/worker_template.go

- Fixed a typo in api server manifest
- wait for hostname to not be "localhost" before starting the kubelet

Hostname wait

---

CHANGELOG.md
files/conf/99-default.rules
pkg/template/master_template.go
pkg/template/worker_template.go

Towards: https://github.com/giantswarm/giantswarm/issues/22498

Override default auditd configuration to capture `execve` syscalls.

---

CHANGELOG.md
pkg/template/master_template.go
pkg/template/worker_template.go

The file `crictl.yaml` was not placed on the worker node correctly.

fix containerd

---

CHANGELOG.md
files/conf/k8s-addons

Remove applying the aws-ccm as a static pod and go for a usual app deployment.

Revert applying aws-cloud-controller-manager

---

files/conf/k8s-addons
pkg/template/types.go
pkg/template/validation.go

Added two flags to avoid installing calico and kube-proxy in a cluster.
This is needed to install CNIs as managed apps.

Allow not installing kube-proxy and calico

---

CHANGELOG.md
files/manifests/k8s-api-server.yaml

On AWS, master nodes have 2 ENIs (network interfaces), one used just for etcd, one used for the rest.
The kubelet binds to the first ethernet card, and does not listen to the other.
When prometheus tries to scrape stuff going through the API server's proxy, it selects the first private IP address as listed in the `Node` resource's status.
There is no guarantee over the order of IP addresses in the node status, and thus scraping can fail or succeed due to randomness.
This PR changes the way the kubelet exposes itself through the proxy, making it prefer the hostname over the private IP address  and hopefully fixing scraping troubles.

Change preferred address type

---

CHANGELOG.md
files/config/kube-proxy.yaml

If there is no calico there should be no `clusterCIDR` field set in kube-proxy's config.
This PR fixes that.

Avoid setting `clusterCIDR` in kube proxy's config if calico is disabled

---

CHANGELOG.md
pkg/template/release.go

Since calico is now opt-out, we don't want to fail while parsing release component versions if calico is not present in the Release CR.
This PR does just that

Optional calico

---

CHANGELOG.md
pkg/template/master_template.go
pkg/template/worker_template.go

Sometimes, azure VMs take some time to have their hostname properly set.
This PR adds a sanity check that ensures the hostname is correct before starting the kubelet.
Without the check, node can't bootstrap correctly

Hostname check

---

CHANGELOG.md
files/k8s-resource/calico-crd-installer.yaml

calico-crd-installer: Tolerate `node.cloudprovider.kubernetes.io/uninitialized`.

---

CHANGELOG.md
files/manifests/k8s-api-server.yaml.tmpl
pkg/template/types.go

Backport of fix released in 14.6.0 to v15
This PR removes IRSA-specific flags and use generic flags for apiserver config regarding service accounts

Irsa remove

---

CHANGELOG.md
files/conf/containerd-config.toml

Fixes https://github.com/giantswarm/giantswarm/issues/24615
We currently missing to set the registry mirror for workload clusters.
The registry mirrors is an array which comes from our config repo, https://github.com/giantswarm/config/blob/main/default/config.yaml#L7.
We should pick the first item to add this into our containerd configuration.
I double checked it on all installations, our China installations won't include this (we overwrite an empty array in those cases).

Add registry mirror

---

CHANGELOG.md
pkg/template/master_template.go

Label master nodes with node-role.kubernetes.io/control-plane 

---

CHANGELOG.md
files/conf/setup-apiserver-environment

The previous strategy we used to allocate memory request for API server static pod was too aggressive.
On azure, that left not enough room for pods to be scheduled in master nodes and lead to broken clusters.
This PR changes how we calculate requests and limits for API server pod and clarifies the reasoning behind the choice.
Tradeoff: fairness limits will be lower on the same hardware

Fix apiserver requests

---

CHANGELOG.md
files/conf/containerd-config.toml

```
crictl -r /run/containerd/containerd.sock pull docker.io/library/alpine:latest
FATA[0002] pulling image: rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/alpine:latest": failed to copy: httpReadSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/library/alpine/manifests/sha256:f271e74b17ced29b915d351685fd4644785c6d1559dd1f2d4189a5e851ef753a: 429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```
Adding to containerd docker auth credentials
```
[plugins."io.containerd.grpc.v1.cri".registry.configs."registry-1.docker.io".auth]
auth = "OMITED" …
```

Use authentication when pulling docker images

---

CHANGELOG.md
files/conf/k8s-addons
files/k8s-resource/calico-crd-installer.yaml

In k8s-addons script we deploy a job + RBAC manifest using kubectl apply.
Before this pr, we only tried once to apply those manifests and in case of error the master node provisioning was failing.
With this PR we retry the apply operation multiple times in case of error to make bootstrap more reliable

Calico job improve

---

CHANGELOG.md
files/config/kubelet-master.yaml.tmpl
files/config/kubelet-worker.yaml.tmpl
files/manifests/k8s-api-server.yaml.tmpl
files/manifests/k8s-controller-manager.yaml
files/manifests/k8s-scheduler.yaml
pkg/template/types.go

The `CronJobTimeZone` feature flag is only available in k8s 1.24+
This PR makes the feature flag configurable so we can bump k8scc on 1.23 clusters

Enable `CronJobTimeZone` feature gate through feature flag.

---

CHANGELOG.md
files/config/kubelet-master.yaml.tmpl
files/config/kubelet-worker.yaml.tmpl
pkg/template/types.go

This feature flag is enabled by default with > k8s 1.23.
Issue: https://github.com/giantswarm/roadmap/issues/2536
See https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/

Remove CSIMigration feature flag

---

CHANGELOG.md
files/manifests/k8s-controller-manager.yaml
pkg/template/types.go

Also change default value from hardcoded `10` to `125` which is 1% of the upstream default of `12500`
Towards https://github.com/giantswarm/klingel/issues/91
for **v16.x.x** a branch from `v16.3.0` was created and the same diff applied in https://github.com/giantswarm/k8scloudconfig/tree/allow-customizing-terminated-pod-gc-threshold-v16

Add support for changing value of `controller-manager` `--terminated-pod-gc-threshold` flag

---

CHANGELOG.md
pkg/template/master_template.go
pkg/template/worker_template.go

Towards https://github.com/giantswarm/giantswarm/issues/24992 this PR enables the auditd systemd unit so customers can have audit logs until teleport is out there

Enable auditd systemd unit

---

go.mod

Removing `replace` lines from go.sum that had no effect as the dependencies are not used.

Remove ineffective replace lines from `go.sum`
